/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * A property value for a specific product property, which may also employ a specific scale.
 *
 * @param valueId The numeric ID of this property value.
 * @param name The name string of this property value.
 * @param scaleId The numeric scale ID of the scale to which this property value belongs.
 * @param equalTo A list of numeric property value IDs this property value is equal to (if any).
 */
@Serializable

data class BuyerTaxonomyPropertyValue (

    /* The numeric ID of this property value. */
    @SerialName(value = "value_id") val valueId: kotlin.Long? = null,

    /* The name string of this property value. */
    @SerialName(value = "name") val name: kotlin.String? = null,

    /* The numeric scale ID of the scale to which this property value belongs. */
    @SerialName(value = "scale_id") val scaleId: kotlin.Long? = null,

    /* A list of numeric property value IDs this property value is equal to (if any). */
    @SerialName(value = "equal_to") val equalTo: kotlin.collections.List<kotlin.Int>? = null

) {


}

