/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * A representation of the associations of variations and images on a listing.
 *
 * @param propertyId The numeric ID of the Property.
 * @param valueId The numeric ID of the Value.
 * @param `value` The string value of the property.
 * @param imageId The numeric ID of the Image.
 */
@Serializable

data class ListingVariationImage (

    /* The numeric ID of the Property. */
    @SerialName(value = "property_id") val propertyId: kotlin.Long? = null,

    /* The numeric ID of the Value. */
    @SerialName(value = "value_id") val valueId: kotlin.Long? = null,

    /* The string value of the property. */
    @SerialName(value = "value") val `value`: kotlin.String? = null,

    /* The numeric ID of the Image. */
    @SerialName(value = "image_id") val imageId: kotlin.Long? = null

) {


}

