/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.models

import com.etsy.models.Money

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * A representation of an offering for a listing.
 *
 * @param offeringId The ID for the ProductOffering
 * @param quantity The quantity the ProductOffering
 * @param isEnabled Whether or not the offering can be shown to buyers.
 * @param isDeleted Whether or not the offering has been deleted.
 * @param price Price data for this ProductOffering
 * @param readinessStateId Processing Profile for this ProductOffering
 */
@Serializable

data class ListingInventoryProductOffering (

    /* The ID for the ProductOffering */
    @SerialName(value = "offering_id") val offeringId: kotlin.Long? = null,

    /* The quantity the ProductOffering */
    @SerialName(value = "quantity") val quantity: kotlin.Int? = null,

    /* Whether or not the offering can be shown to buyers. */
    @SerialName(value = "is_enabled") val isEnabled: kotlin.Boolean? = null,

    /* Whether or not the offering has been deleted. */
    @SerialName(value = "is_deleted") val isDeleted: kotlin.Boolean? = null,

    /* Price data for this ProductOffering */
    @SerialName(value = "price") val price: Money? = null,

    /* Processing Profile for this ProductOffering */
    @SerialName(value = "readiness_state_id") val readinessStateId: kotlin.Long? = null

) {


}

