/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Reference urls and metadata for a video associated with a specific listing.
 *
 * @param videoId The unique ID of a video associated with a listing.
 * @param height The video height dimension in pixels.
 * @param width The video width dimension in pixels.
 * @param thumbnailUrl The url of the video thumbnail.
 * @param videoUrl The url of the video file.
 * @param videoState The current state of a given video. Value is one of `active`, `inactive`, `deleted` or `flagged`.
 */
@Serializable

data class ListingVideo (

    /* The unique ID of a video associated with a listing. */
    @SerialName(value = "video_id") val videoId: kotlin.Long? = null,

    /* The video height dimension in pixels. */
    @SerialName(value = "height") val height: kotlin.Int? = null,

    /* The video width dimension in pixels. */
    @SerialName(value = "width") val width: kotlin.Int? = null,

    /* The url of the video thumbnail. */
    @SerialName(value = "thumbnail_url") val thumbnailUrl: kotlin.String? = null,

    /* The url of the video file. */
    @SerialName(value = "video_url") val videoUrl: kotlin.String? = null,

    /* The current state of a given video. Value is one of `active`, `inactive`, `deleted` or `flagged`. */
    @SerialName(value = "video_state") val videoState: ListingVideo.VideoState? = null

) {

    /**
     * The current state of a given video. Value is one of `active`, `inactive`, `deleted` or `flagged`.
     *
     * Values: active,inactive,deleted,flagged
     */
    @Serializable
    enum class VideoState(val value: kotlin.String) {
        @SerialName(value = "active") active("active"),
        @SerialName(value = "inactive") inactive("inactive"),
        @SerialName(value = "deleted") deleted("deleted"),
        @SerialName(value = "flagged") flagged("flagged");
    }

}

