/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Represents the translation data for a Listing.
 *
 * @param listingId The numeric ID for the Listing.
 * @param language The IETF language tag (e.g. 'fr') for the language of this translation.
 * @param title The title of the Listing of this Translation.
 * @param description The description of the Listing of this Translation.
 * @param tags The tags of the Listing of this Translation.
 */
@Serializable

data class ListingTranslation (

    /* The numeric ID for the Listing. */
    @SerialName(value = "listing_id") val listingId: kotlin.Long? = null,

    /* The IETF language tag (e.g. 'fr') for the language of this translation. */
    @SerialName(value = "language") val language: kotlin.String? = null,

    /* The title of the Listing of this Translation. */
    @SerialName(value = "title") val title: kotlin.String? = null,

    /* The description of the Listing of this Translation. */
    @SerialName(value = "description") val description: kotlin.String? = null,

    /* The tags of the Listing of this Translation. */
    @SerialName(value = "tags") val tags: kotlin.collections.List<kotlin.String>? = null

) {


}

