/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.models

import com.etsy.models.ListingVideo

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Represents a list of listing video resources, each of which contains the reference URLs for the videos.
 *
 * @param count The number of results.
 * @param results The list of requested resources.
 */
@Serializable

data class ListingVideos (

    /* The number of results. */
    @SerialName(value = "count") val count: kotlin.Int? = null,

    /* The list of requested resources. */
    @SerialName(value = "results") val results: kotlin.collections.List<ListingVideo>? = null

) {


}

