/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * A listing review record left by a User.
 *
 * @param shopId The shop's numeric ID.
 * @param listingId The ID of the ShopListing that the TransactionReview belongs to.
 * @param rating Rating value on scale from 1 to 5
 * @param review A message left by the author, explaining the feedback, if provided.
 * @param language The language of the TransactionReview
 * @param imageUrlFullxfull The url to a photo provided with the feedback, dimensions fullxfull. Note: This field may be absent, depending on the buyer's privacy settings.
 * @param createTimestamp The date and time the TransactionReview was created in epoch seconds.
 * @param createdTimestamp The date and time the TransactionReview was created in epoch seconds.
 * @param updateTimestamp The date and time the TransactionReview was updated in epoch seconds.
 * @param updatedTimestamp The date and time the TransactionReview was updated in epoch seconds.
 */
@Serializable

data class ListingReview (

    /* The shop's numeric ID. */
    @SerialName(value = "shop_id") val shopId: kotlin.Long? = null,

    /* The ID of the ShopListing that the TransactionReview belongs to. */
    @SerialName(value = "listing_id") val listingId: kotlin.Long? = null,

    /* Rating value on scale from 1 to 5 */
    @SerialName(value = "rating") val rating: kotlin.Int? = null,

    /* A message left by the author, explaining the feedback, if provided. */
    @SerialName(value = "review") val review: kotlin.String? = null,

    /* The language of the TransactionReview */
    @SerialName(value = "language") val language: kotlin.String? = null,

    /* The url to a photo provided with the feedback, dimensions fullxfull. Note: This field may be absent, depending on the buyer's privacy settings. */
    @SerialName(value = "image_url_fullxfull") val imageUrlFullxfull: kotlin.String? = null,

    /* The date and time the TransactionReview was created in epoch seconds. */
    @SerialName(value = "create_timestamp") val createTimestamp: kotlin.Int? = null,

    /* The date and time the TransactionReview was created in epoch seconds. */
    @SerialName(value = "created_timestamp") val createdTimestamp: kotlin.Int? = null,

    /* The date and time the TransactionReview was updated in epoch seconds. */
    @SerialName(value = "update_timestamp") val updateTimestamp: kotlin.Int? = null,

    /* The date and time the TransactionReview was updated in epoch seconds. */
    @SerialName(value = "updated_timestamp") val updatedTimestamp: kotlin.Int? = null

) {


}

