/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.models

import com.etsy.models.PaymentAccountLedgerEntry

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * A set of PaymentAccountLedgerEntry resources
 *
 * @param count The number of PaymentAccountLedgerEntry resources found.
 * @param results The PaymentAccountLedgerEntry resources found.
 */
@Serializable

data class PaymentAccountLedgerEntries (

    /* The number of PaymentAccountLedgerEntry resources found. */
    @SerialName(value = "count") val count: kotlin.Int? = null,

    /* The PaymentAccountLedgerEntry resources found. */
    @SerialName(value = "results") val results: kotlin.collections.List<PaymentAccountLedgerEntry>? = null

) {


}

