/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.models

import com.etsy.models.PaymentAdjustment

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Represents an entry in a shop's ledger.
 *
 * @param entryId The ledger entry's numeric ID.
 * @param ledgerId The ledger's numeric ID.
 * @param sequenceNumber The sequence allows ledger entries to be sorted chronologically. The higher the sequence, the more recent the entry.
 * @param amount The amount of money credited to the ledger.
 * @param currency The currency of the entry on the ledger.
 * @param description Details what kind of ledger entry this is: a payment, refund, reversal of a failed refund, disbursement, returned disbursement, recoupment, miscellaneous credit, miscellaneous debit, or bill payment.
 * @param balance The amount of money in the shop's ledger the moment after this entry was applied.
 * @param createDate The date and time the ledger entry was created in Epoch seconds.
 * @param createdTimestamp The date and time the ledger entry was created in Epoch seconds.
 * @param ledgerType The original reference type for the ledger entry.
 * @param referenceType The object type the ledger entry refers to.
 * @param referenceId The object id the ledger entry refers to.
 * @param paymentAdjustments List of refund objects on an Etsy Payments transaction. All monetary amounts are in USD pennies unless otherwise specified.
 */
@Serializable

data class PaymentAccountLedgerEntry (

    /* The ledger entry's numeric ID. */
    @SerialName(value = "entry_id") val entryId: kotlin.Long? = null,

    /* The ledger's numeric ID. */
    @SerialName(value = "ledger_id") val ledgerId: kotlin.Long? = null,

    /* The sequence allows ledger entries to be sorted chronologically. The higher the sequence, the more recent the entry. */
    @SerialName(value = "sequence_number") val sequenceNumber: kotlin.Int? = null,

    /* The amount of money credited to the ledger. */
    @SerialName(value = "amount") val amount: kotlin.Int? = null,

    /* The currency of the entry on the ledger. */
    @SerialName(value = "currency") val currency: kotlin.String? = null,

    /* Details what kind of ledger entry this is: a payment, refund, reversal of a failed refund, disbursement, returned disbursement, recoupment, miscellaneous credit, miscellaneous debit, or bill payment. */
    @SerialName(value = "description") val description: kotlin.String? = null,

    /* The amount of money in the shop's ledger the moment after this entry was applied. */
    @SerialName(value = "balance") val balance: kotlin.Int? = null,

    /* The date and time the ledger entry was created in Epoch seconds. */
    @SerialName(value = "create_date") val createDate: kotlin.Int? = null,

    /* The date and time the ledger entry was created in Epoch seconds. */
    @SerialName(value = "created_timestamp") val createdTimestamp: kotlin.Int? = null,

    /* The original reference type for the ledger entry. */
    @SerialName(value = "ledger_type") val ledgerType: kotlin.String? = null,

    /* The object type the ledger entry refers to. */
    @SerialName(value = "reference_type") val referenceType: kotlin.String? = null,

    /* The object id the ledger entry refers to. */
    @SerialName(value = "reference_id") val referenceId: kotlin.String? = null,

    /* List of refund objects on an Etsy Payments transaction. All monetary amounts are in USD pennies unless otherwise specified. */
    @SerialName(value = "payment_adjustments") val paymentAdjustments: kotlin.collections.List<PaymentAdjustment>? = null

) {


}

