/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * A payemnt adjustment line item for a payment adjustment.
 *
 * @param paymentAdjustmentId The numeric ID for a payment adjustment.
 * @param paymentAdjustmentItemId Unique ID for the adjustment line item.
 * @param adjustmentType String indicating the type of adjustment for this line item.
 * @param amount Integer value for the amount of the adjustment in original currency.
 * @param shopAmount Integer value for the amount of the adjustment in currency for the shop.
 * @param transactionId The unique numeric ID for a transaction.
 * @param billPaymentId Unique ID for the bill payment adjustment.
 * @param createdTimestamp The transaction's creation date and time, in epoch seconds.
 * @param updatedTimestamp The update date and time the payment adjustment in epoch seconds.
 */
@Serializable

data class PaymentAdjustmentItem (

    /* The numeric ID for a payment adjustment. */
    @SerialName(value = "payment_adjustment_id") val paymentAdjustmentId: kotlin.Long? = null,

    /* Unique ID for the adjustment line item. */
    @SerialName(value = "payment_adjustment_item_id") val paymentAdjustmentItemId: kotlin.Long? = null,

    /* String indicating the type of adjustment for this line item. */
    @SerialName(value = "adjustment_type") val adjustmentType: kotlin.String? = null,

    /* Integer value for the amount of the adjustment in original currency. */
    @SerialName(value = "amount") val amount: kotlin.Int? = 0,

    /* Integer value for the amount of the adjustment in currency for the shop. */
    @SerialName(value = "shop_amount") val shopAmount: kotlin.Int? = 0,

    /* The unique numeric ID for a transaction. */
    @SerialName(value = "transaction_id") val transactionId: kotlin.Long? = null,

    /* Unique ID for the bill payment adjustment. */
    @SerialName(value = "bill_payment_id") val billPaymentId: kotlin.Long? = null,

    /* The transaction's creation date and time, in epoch seconds. */
    @SerialName(value = "created_timestamp") val createdTimestamp: kotlin.Int? = null,

    /* The update date and time the payment adjustment in epoch seconds. */
    @SerialName(value = "updated_timestamp") val updatedTimestamp: kotlin.Int? = null

) {


}

