/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.models

import com.etsy.models.Payment

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Represents several payments made with Etsy Payments. All monetary amounts are in USD pennies unless otherwise specified.
 *
 * @param count The number of payments in the response.
 * @param results A list of payments.
 */
@Serializable

data class Payments (

    /* The number of payments in the response. */
    @SerialName(value = "count") val count: kotlin.Int? = null,

    /* A list of payments. */
    @SerialName(value = "results") val results: kotlin.collections.List<Payment>? = null

) {


}

