/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * A confirmation that the current application has access to the Open API
 *
 * @param applicationId The authenticated application's ID
 */
@Serializable

data class Pong (

    /* The authenticated application's ID */
    @SerialName(value = "application_id") val applicationId: kotlin.Long? = null

) {


}

