/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Represents a single user of the site
 *
 * @param userId The numeric ID of a user. This number is also a valid shop ID for the user's shop.
 * @param shopId The unique positive non-zero numeric ID for an Etsy Shop.
 */
@Serializable

data class Self (

    /* The numeric ID of a user. This number is also a valid shop ID for the user's shop. */
    @SerialName(value = "user_id") val userId: kotlin.Long? = null,

    /* The unique positive non-zero numeric ID for an Etsy Shop. */
    @SerialName(value = "shop_id") val shopId: kotlin.Long? = null

) {


}

