/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.models

import com.etsy.models.SellerTaxonomyNode

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * A list of taxonomy nodes from the seller taxonomy tree.
 *
 * @param count The number of results.
 * @param results The list of requested resources.
 */
@Serializable

data class SellerTaxonomyNodes (

    /* The number of results. */
    @SerialName(value = "count") val count: kotlin.Int? = null,

    /* The list of requested resources. */
    @SerialName(value = "results") val results: kotlin.collections.List<SellerTaxonomyNode>? = null

) {


}

