/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * A shipping carrier's mail class, which is used to calculate an Estimated Delivery Date.
 *
 * @param mailClassKey The unique identifier of this mail class.
 * @param name The name of this mail class.
 */
@Serializable

data class ShippingCarrierMailClass (

    /* The unique identifier of this mail class. */
    @SerialName(value = "mail_class_key") val mailClassKey: kotlin.String? = null,

    /* The name of this mail class. */
    @SerialName(value = "name") val name: kotlin.String? = null

) {


}

