/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.models

import com.etsy.models.ShippingCarrier

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Represents several ShippingCarriers.
 *
 * @param count 
 * @param results 
 */
@Serializable

data class ShippingCarriers (

    @SerialName(value = "count") val count: kotlin.Int? = null,

    @SerialName(value = "results") val results: kotlin.collections.List<ShippingCarrier>? = null

) {


}

