/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Represents a processing profile to set a product offering's readiness state and processing time info.
 *
 * @param shopId The unique positive non-zero numeric ID for an Etsy Shop.
 * @param readinessStateId The numeric ID of the [processing profile](/documentation/reference#operation/getShopReadinessStateDefinition) associated with the listing. Required when listing type is `physical`.
 * @param readinessState The readiness state of a product: \\\"1\\\" means \\\"ready_to_ship\\\", and \\\"2\\\" means \\\"made_to_order\\\"
 * @param minProcessingDays The minimum number of days for processing a specific product.
 * @param maxProcessingDays The maximum number of days for processing a specific product.
 * @param processingDaysDisplayLabel Translated display label string for processing days, for example \"3 - 5 days\".
 */
@Serializable

data class ShopProcessingProfile (

    /* The unique positive non-zero numeric ID for an Etsy Shop. */
    @SerialName(value = "shop_id") val shopId: kotlin.Long? = null,

    /* The numeric ID of the [processing profile](/documentation/reference#operation/getShopReadinessStateDefinition) associated with the listing. Required when listing type is `physical`. */
    @SerialName(value = "readiness_state_id") val readinessStateId: kotlin.Long? = null,

    /* The readiness state of a product: \\\"1\\\" means \\\"ready_to_ship\\\", and \\\"2\\\" means \\\"made_to_order\\\" */
    @SerialName(value = "readiness_state") val readinessState: ShopProcessingProfile.ReadinessState? = null,

    /* The minimum number of days for processing a specific product. */
    @SerialName(value = "min_processing_days") val minProcessingDays: kotlin.Int? = null,

    /* The maximum number of days for processing a specific product. */
    @SerialName(value = "max_processing_days") val maxProcessingDays: kotlin.Int? = null,

    /* Translated display label string for processing days, for example \"3 - 5 days\". */
    @SerialName(value = "processing_days_display_label") val processingDaysDisplayLabel: kotlin.String? = null

) {

    /**
     * The readiness state of a product: \\\"1\\\" means \\\"ready_to_ship\\\", and \\\"2\\\" means \\\"made_to_order\\\"
     *
     * Values: ready_to_ship,made_to_order
     */
    @Serializable
    enum class ReadinessState(val value: kotlin.String) {
        @SerialName(value = "ready_to_ship") ready_to_ship("ready_to_ship"),
        @SerialName(value = "made_to_order") made_to_order("made_to_order");
    }

}

