/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.models

import com.etsy.models.ShopReceipt

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * The receipts for a specific Shop.
 *
 * @param count The number of Shop Receipts found.
 * @param results List of Shop Receipt resources found, with all Shop Receipt fields for each resource.
 */
@Serializable

data class ShopReceipts (

    /* The number of Shop Receipts found. */
    @SerialName(value = "count") val count: kotlin.Int? = null,

    /* List of Shop Receipt resources found, with all Shop Receipt fields for each resource. */
    @SerialName(value = "results") val results: kotlin.collections.List<ShopReceipt>? = null

) {


}

