/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.models

import com.etsy.models.Money

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * A representation of a shipping profile upgrade option.
 *
 * @param shippingProfileId The numeric ID of the base shipping profile.
 * @param upgradeId The numeric ID that is associated with a shipping upgrade
 * @param upgradeName Name for the shipping upgrade shown to shoppers at checkout, e.g. USPS Priority.
 * @param type The type of the shipping upgrade. Domestic (0) or international (1).
 * @param rank The positive non-zero numeric position in the images displayed in a listing, with rank 1 images appearing in the left-most position in a listing.
 * @param language The IETF language tag for the language of the shipping profile. Ex: `de`, `en`, `es`, `fr`, `it`, `ja`, `nl`, `pl`, `pt`
 * @param price Additional cost of adding the shipping upgrade.
 * @param secondaryPrice Additional cost of adding the shipping upgrade for each additional item.
 * @param shippingCarrierId The unique ID of a supported shipping carrier, which is used to calculate an Estimated Delivery Date. **Required with `mail_class`** if `min_delivery_days` and `max_delivery_days` are null.
 * @param mailClass The unique ID string of a shipping carrier's mail class, which is used to calculate an estimated delivery date. **Required with `shipping_carrier_id`** if `min_delivery_days` and `max_delivery_days` are null.
 * @param minDeliveryDays The minimum number of business days a buyer can expect to wait to receive their purchased item once it has shipped. **Required with `max_delivery_days`** if `mail_class` is null.
 * @param maxDeliveryDays The maximum number of business days a buyer can expect to wait to receive their purchased item once it has shipped. **Required with `min_delivery_days`** if `mail_class` is null.
 */
@Serializable

data class ShopShippingProfileUpgrade (

    /* The numeric ID of the base shipping profile. */
    @SerialName(value = "shipping_profile_id") val shippingProfileId: kotlin.Long? = null,

    /* The numeric ID that is associated with a shipping upgrade */
    @SerialName(value = "upgrade_id") val upgradeId: kotlin.Long? = null,

    /* Name for the shipping upgrade shown to shoppers at checkout, e.g. USPS Priority. */
    @SerialName(value = "upgrade_name") val upgradeName: kotlin.String? = null,

    /* The type of the shipping upgrade. Domestic (0) or international (1). */
    @SerialName(value = "type") val type: ShopShippingProfileUpgrade.Type? = null,

    /* The positive non-zero numeric position in the images displayed in a listing, with rank 1 images appearing in the left-most position in a listing. */
    @SerialName(value = "rank") val rank: kotlin.Int? = null,

    /* The IETF language tag for the language of the shipping profile. Ex: `de`, `en`, `es`, `fr`, `it`, `ja`, `nl`, `pl`, `pt` */
    @SerialName(value = "language") val language: kotlin.String? = null,

    /* Additional cost of adding the shipping upgrade. */
    @SerialName(value = "price") val price: Money? = null,

    /* Additional cost of adding the shipping upgrade for each additional item. */
    @SerialName(value = "secondary_price") val secondaryPrice: Money? = null,

    /* The unique ID of a supported shipping carrier, which is used to calculate an Estimated Delivery Date. **Required with `mail_class`** if `min_delivery_days` and `max_delivery_days` are null. */
    @SerialName(value = "shipping_carrier_id") val shippingCarrierId: kotlin.Int? = null,

    /* The unique ID string of a shipping carrier's mail class, which is used to calculate an estimated delivery date. **Required with `shipping_carrier_id`** if `min_delivery_days` and `max_delivery_days` are null. */
    @SerialName(value = "mail_class") val mailClass: kotlin.String? = null,

    /* The minimum number of business days a buyer can expect to wait to receive their purchased item once it has shipped. **Required with `max_delivery_days`** if `mail_class` is null. */
    @SerialName(value = "min_delivery_days") val minDeliveryDays: kotlin.Int? = null,

    /* The maximum number of business days a buyer can expect to wait to receive their purchased item once it has shipped. **Required with `min_delivery_days`** if `mail_class` is null. */
    @SerialName(value = "max_delivery_days") val maxDeliveryDays: kotlin.Int? = null

) {

    /**
     * The type of the shipping upgrade. Domestic (0) or international (1).
     *
     * Values: _0,_1
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "0") _0("0"),
        @SerialName(value = "1") _1("1");
    }

}

