/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.models

import com.etsy.models.ShopListing

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * A set of ShopListing resources.
 *
 * @param count The number of ShopListing resources found.
 * @param results The ShopListing resources found.
 */
@Serializable

data class ShopListings (

    /* The number of ShopListing resources found. */
    @SerialName(value = "count") val count: kotlin.Int? = null,

    /* The ShopListing resources found. */
    @SerialName(value = "results") val results: kotlin.collections.List<ShopListing>? = null

) {


}

