/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * A section within a shop, into which a user can sort listings.
 *
 * @param shopSectionId The numeric ID of a section in a specific Etsy shop.
 * @param title The title string for a shop section.
 * @param rank The positive non-zero numeric position of this section in the section display order for a shop, with rank 1 sections appearing first.
 * @param userId The numeric ID of the [user](/documentation/reference#tag/User) who owns this shop section.
 * @param activeListingCount The number of active listings in one section of a specific Etsy shop.
 */
@Serializable

data class ShopSection (

    /* The numeric ID of a section in a specific Etsy shop. */
    @SerialName(value = "shop_section_id") val shopSectionId: kotlin.Long? = null,

    /* The title string for a shop section. */
    @SerialName(value = "title") val title: kotlin.String? = null,

    /* The positive non-zero numeric position of this section in the section display order for a shop, with rank 1 sections appearing first. */
    @SerialName(value = "rank") val rank: kotlin.Int? = null,

    /* The numeric ID of the [user](/documentation/reference#tag/User) who owns this shop section. */
    @SerialName(value = "user_id") val userId: kotlin.Long? = null,

    /* The number of active listings in one section of a specific Etsy shop. */
    @SerialName(value = "active_listing_count") val activeListingCount: kotlin.Int? = null

) {


}

