/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.models

import com.etsy.models.Money

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * The refund record for a receipt.
 *
 * @param amount A number equal to the refund total.
 * @param createdTimestamp The date & time of the refund, in epoch seconds.
 * @param reason The reason string given for the refund.
 * @param noteFromIssuer The note string created by the refund issuer.
 * @param status The status indication string for the refund.
 */
@Serializable

data class ShopRefund (

    /* A number equal to the refund total. */
    @SerialName(value = "amount") val amount: Money? = null,

    /* The date & time of the refund, in epoch seconds. */
    @SerialName(value = "created_timestamp") val createdTimestamp: kotlin.Int? = null,

    /* The reason string given for the refund. */
    @SerialName(value = "reason") val reason: kotlin.String? = null,

    /* The note string created by the refund issuer. */
    @SerialName(value = "note_from_issuer") val noteFromIssuer: kotlin.String? = null,

    /* The status indication string for the refund. */
    @SerialName(value = "status") val status: kotlin.String? = null

) {


}

