/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.models

import com.etsy.models.TaxonomyPropertyScale
import com.etsy.models.TaxonomyPropertyValue

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * A product property definition.
 *
 * @param propertyId The unique numeric ID of this product property.
 * @param name The name string for this taxonomy node.
 * @param displayName The human-readable product property name string.
 * @param scales A list of available scales.
 * @param isRequired When true, listings assigned eligible taxonomy IDs require this property.
 * @param supportsAttributes When true, you can use this property in listing attributes.
 * @param supportsVariations When true, you can use this property in listing variations.
 * @param isMultivalued When true, you can assign multiple property values to this property
 * @param maxValuesAllowed When true, you can assign multiple property values to this property
 * @param possibleValues A list of supported property value strings for this property.
 * @param selectedValues A list of property value strings automatically and always selected for the given property.
 */
@Serializable

data class TaxonomyNodeProperty (

    /* The unique numeric ID of this product property. */
    @SerialName(value = "property_id") val propertyId: kotlin.Long? = null,

    /* The name string for this taxonomy node. */
    @SerialName(value = "name") val name: kotlin.String? = null,

    /* The human-readable product property name string. */
    @SerialName(value = "display_name") val displayName: kotlin.String? = null,

    /* A list of available scales. */
    @SerialName(value = "scales") val scales: kotlin.collections.List<TaxonomyPropertyScale>? = null,

    /* When true, listings assigned eligible taxonomy IDs require this property. */
    @SerialName(value = "is_required") val isRequired: kotlin.Boolean? = null,

    /* When true, you can use this property in listing attributes. */
    @SerialName(value = "supports_attributes") val supportsAttributes: kotlin.Boolean? = null,

    /* When true, you can use this property in listing variations. */
    @SerialName(value = "supports_variations") val supportsVariations: kotlin.Boolean? = null,

    /* When true, you can assign multiple property values to this property */
    @SerialName(value = "is_multivalued") val isMultivalued: kotlin.Boolean? = null,

    /* When true, you can assign multiple property values to this property */
    @SerialName(value = "max_values_allowed") val maxValuesAllowed: kotlin.Int? = null,

    /* A list of supported property value strings for this property. */
    @SerialName(value = "possible_values") val possibleValues: kotlin.collections.List<TaxonomyPropertyValue>? = null,

    /* A list of property value strings automatically and always selected for the given property. */
    @SerialName(value = "selected_values") val selectedValues: kotlin.collections.List<TaxonomyPropertyValue>? = null

) {


}

