/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * A scale defnining the assignable increments for the property values available to specific product properties.
 *
 * @param scaleId The unique numeric ID of a scale.
 * @param displayName The name string for a scale.
 * @param description The description string for a scale.
 */
@Serializable

data class TaxonomyPropertyScale (

    /* The unique numeric ID of a scale. */
    @SerialName(value = "scale_id") val scaleId: kotlin.Long? = null,

    /* The name string for a scale. */
    @SerialName(value = "display_name") val displayName: kotlin.String? = null,

    /* The description string for a scale. */
    @SerialName(value = "description") val description: kotlin.String? = null

) {


}

