/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * A list of variations chosen by the buyer during checkout.
 *
 * @param propertyId The variation property ID.
 * @param valueId The ID of the variation value selected.
 * @param formattedName Formatted name of the variation.
 * @param formattedValue Value of the variation entered by the buyer.
 */
@Serializable

data class TransactionVariations (

    /* The variation property ID. */
    @SerialName(value = "property_id") val propertyId: kotlin.Int? = null,

    /* The ID of the variation value selected. */
    @SerialName(value = "value_id") val valueId: kotlin.Int? = null,

    /* Formatted name of the variation. */
    @SerialName(value = "formatted_name") val formattedName: kotlin.String? = null,

    /* Value of the variation entered by the buyer. */
    @SerialName(value = "formatted_value") val formattedValue: kotlin.String? = null

) {


}

