/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.models

import com.etsy.models.TransactionReview

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * A set of transaction review records left by Users.
 *
 * @param count The number of TransactionReview resources found.
 * @param results The TransactionReview resources found.
 */
@Serializable

data class TransactionReviews (

    /* The number of TransactionReview resources found. */
    @SerialName(value = "count") val count: kotlin.Int? = null,

    /* The TransactionReview resources found. */
    @SerialName(value = "results") val results: kotlin.collections.List<TransactionReview>? = null

) {


}

