/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param type field used to determine the type of the object when deserializing union type responses
 */
@Serializable

data class TypeDiscriminator (

    /* field used to determine the type of the object when deserializing union type responses */
    @SerialName(value = "__type") @Required val type: kotlin.String

) {


}

