/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param propertyId 
 * @param valueId 
 * @param imageId 
 */
@Serializable

data class UpdateVariationImagesRequestVariationImagesInner (

    @SerialName(value = "property_id") @Required val propertyId: kotlin.Long,

    @SerialName(value = "value_id") @Required val valueId: kotlin.Long,

    @SerialName(value = "image_id") @Required val imageId: kotlin.Long

) {


}

