/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param propertyId The unique ID of an Etsy [listing property](/documentation/reference#operation/getListingProperties).
 * @param valueIds An array of unique IDs of multiple Etsy [listing property](/documentation/reference#operation/getListingProperties) values. For example, if your listing offers different sizes of a product, then the value ID list contains value IDs for each size.
 * @param propertyValues A list of property value entries for this product. Note: parenthesis characters (`(` and `)`) are not allowed.
 * @param scaleId The numeric ID of a single Etsy.com measurement scale. For example, for shoe size, there are three `scale_id`s available - `UK`, `US/Canada`, and `EU`, where `US/Canada` has `scale_id` 19.
 * @param propertyName The name of the property, in the requested locale language.
 */
@Serializable

data class UpdateListingInventoryRequestProductsInnerPropertyValuesInner (

    /* The unique ID of an Etsy [listing property](/documentation/reference#operation/getListingProperties). */
    @SerialName(value = "property_id") @Required val propertyId: kotlin.Long,

    /* An array of unique IDs of multiple Etsy [listing property](/documentation/reference#operation/getListingProperties) values. For example, if your listing offers different sizes of a product, then the value ID list contains value IDs for each size. */
    @SerialName(value = "value_ids") @Required val valueIds: kotlin.collections.List<kotlin.Long>,

    /* A list of property value entries for this product. Note: parenthesis characters (`(` and `)`) are not allowed. */
    @SerialName(value = "values") @Required val propertyValues: kotlin.collections.List<kotlin.String>,

    /* The numeric ID of a single Etsy.com measurement scale. For example, for shoe size, there are three `scale_id`s available - `UK`, `US/Canada`, and `EU`, where `US/Canada` has `scale_id` 19. */
    @SerialName(value = "scale_id") val scaleId: kotlin.Long? = null,

    /* The name of the property, in the requested locale language. */
    @SerialName(value = "property_name") val propertyName: kotlin.String? = null

) {


}

