/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.models

import com.etsy.models.UpdateVariationImagesRequestVariationImagesInner

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param variationImages A list of variation image data.
 */
@Serializable

data class UpdateVariationImagesRequest (

    /* A list of variation image data. */
    @SerialName(value = "variation_images") @Required val variationImages: kotlin.collections.List<UpdateVariationImagesRequestVariationImagesInner>

) {


}

