/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.models

import com.etsy.models.UpdateListingInventoryRequestProductsInnerOfferingsInner
import com.etsy.models.UpdateListingInventoryRequestProductsInnerPropertyValuesInner

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param offerings A list of product offering entries for this product.
 * @param sku The SKU string for the product
 * @param propertyValues A list of property value entries for this product. Note: parenthesis characters (`(` and `)`) are not allowed.
 */
@Serializable

data class UpdateListingInventoryRequestProductsInner (

    /* A list of product offering entries for this product. */
    @SerialName(value = "offerings") @Required val offerings: kotlin.collections.List<UpdateListingInventoryRequestProductsInnerOfferingsInner>,

    /* The SKU string for the product */
    @SerialName(value = "sku") val sku: kotlin.String? = null,

    /* A list of property value entries for this product. Note: parenthesis characters (`(` and `)`) are not allowed. */
    @SerialName(value = "property_values") val propertyValues: kotlin.collections.List<UpdateListingInventoryRequestProductsInnerPropertyValuesInner>? = null

) {


}

