/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Represents a single user of the site
 *
 * @param userId The numeric ID of a user. This number is also a valid shop ID for the user's shop.
 * @param primaryEmail An email address string for the user's primary email address. Access to this field is granted on a case by case basis for third-party integrations that require full access
 * @param firstName The user's first name.
 * @param lastName The user's last name.
 * @param imageUrl75x75 The user's avatar URL.
 */
@Serializable

data class User (

    /* The numeric ID of a user. This number is also a valid shop ID for the user's shop. */
    @SerialName(value = "user_id") val userId: kotlin.Long? = null,

    /* An email address string for the user's primary email address. Access to this field is granted on a case by case basis for third-party integrations that require full access */
    @SerialName(value = "primary_email") val primaryEmail: kotlin.String? = null,

    /* The user's first name. */
    @SerialName(value = "first_name") val firstName: kotlin.String? = null,

    /* The user's last name. */
    @SerialName(value = "last_name") val lastName: kotlin.String? = null,

    /* The user's avatar URL. */
    @SerialName(value = "image_url_75x75") val imageUrl75x75: kotlin.String? = null

) {


}

