/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Represents a user's address.
 *
 * @param userAddressId The numeric ID of the user's address.
 * @param userId The user's numeric ID.
 * @param name The user's name for this address.
 * @param firstLine The first line of the user's address.
 * @param secondLine The second line of the user's address.
 * @param city The city field of the user's address.
 * @param state The state field of the user's address.
 * @param zip The zip code field of the user's address.
 * @param isoCountryCode The ISO code of the country in this address.
 * @param countryName The name of the user's country.
 * @param isDefaultShippingAddress Is this the user's default shipping address.
 */
@Serializable

data class UserAddress (

    /* The numeric ID of the user's address. */
    @SerialName(value = "user_address_id") val userAddressId: kotlin.Long? = null,

    /* The user's numeric ID. */
    @SerialName(value = "user_id") val userId: kotlin.Long? = null,

    /* The user's name for this address. */
    @SerialName(value = "name") val name: kotlin.String? = null,

    /* The first line of the user's address. */
    @SerialName(value = "first_line") val firstLine: kotlin.String? = null,

    /* The second line of the user's address. */
    @SerialName(value = "second_line") val secondLine: kotlin.String? = null,

    /* The city field of the user's address. */
    @SerialName(value = "city") val city: kotlin.String? = null,

    /* The state field of the user's address. */
    @SerialName(value = "state") val state: kotlin.String? = null,

    /* The zip code field of the user's address. */
    @SerialName(value = "zip") val zip: kotlin.String? = null,

    /* The ISO code of the country in this address. */
    @SerialName(value = "iso_country_code") val isoCountryCode: kotlin.String? = null,

    /* The name of the user's country. */
    @SerialName(value = "country_name") val countryName: kotlin.String? = null,

    /* Is this the user's default shipping address. */
    @SerialName(value = "is_default_shipping_address") val isDefaultShippingAddress: kotlin.Boolean? = null

) {


}

