/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.apis

import com.etsy.models.ErrorSchema
import com.etsy.models.ShippingCarriers
import com.etsy.models.ShopShippingProfile
import com.etsy.models.ShopShippingProfileDestination
import com.etsy.models.ShopShippingProfileDestinations
import com.etsy.models.ShopShippingProfileUpgrade
import com.etsy.models.ShopShippingProfileUpgrades
import com.etsy.models.ShopShippingProfiles

import com.etsy.infrastructure.*
import io.ktor.client.HttpClient
import io.ktor.client.HttpClientConfig
import io.ktor.client.request.forms.formData
import io.ktor.client.engine.HttpClientEngine
import kotlinx.serialization.json.Json
import io.ktor.http.ParametersBuilder
import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

open class ShopShippingProfileApi : ApiClient {

    constructor(
        baseUrl: String = ApiClient.BASE_URL,
        httpClientEngine: HttpClientEngine? = null,
        httpClientConfig: ((HttpClientConfig<*>) -> Unit)? = null,
        jsonSerializer: Json = ApiClient.JSON_DEFAULT
    ) : super(baseUrl = baseUrl, httpClientEngine = httpClientEngine, httpClientConfig = httpClientConfig, jsonBlock = jsonSerializer)

    constructor(
        baseUrl: String,
        httpClient: HttpClient
    ): super(baseUrl = baseUrl, httpClient = httpClient)


    /**
     * enum for parameter processingTimeUnit
     */
    @Serializable
    enum class ProcessingTimeUnitCreateShopShippingProfile(val value: kotlin.String) {
        
        @SerialName(value = "business_days")
        business_days("business_days"),
        
        @SerialName(value = "weeks")
        weeks("weeks")
        
    }


    /**
     * enum for parameter destinationRegion
     */
    @Serializable
    enum class DestinationRegionCreateShopShippingProfile(val value: kotlin.String) {
        
        @SerialName(value = "eu")
        eu("eu"),
        
        @SerialName(value = "non_eu")
        non_eu("non_eu"),
        
        @SerialName(value = "none")
        none("none")
        
    }

    /**
     * 
     * &lt;div class&#x3D;\&quot;wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\&quot;&gt;&lt;span class&#x3D;\&quot;wt-badge wt-badge--notificationPrimary wt-bg-slime-tint wt-mr-xs-2\&quot;&gt;General Release&lt;/span&gt;&lt;a class&#x3D;\&quot;wt-text-link\&quot; href&#x3D;\&quot;https://github.com/etsy/open-api/discussions\&quot; target&#x3D;\&quot;_blank\&quot; rel&#x3D;\&quot;noopener noreferrer\&quot;&gt;Report bug&lt;/a&gt;&lt;/div&gt;&lt;div class&#x3D;\&quot;wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\&quot;&gt;&lt;p class&#x3D;\&quot;wt-text-body-01 banner-text\&quot;&gt;This endpoint is ready for production use.&lt;/p&gt;&lt;/div&gt;  Creates a new ShippingProfile. You can pass a country iso code or a region when creating a ShippingProfile, but not both. Only one is required. You must pass either a shipping_carrier_id AND mail_class, or both min and max_delivery_days.
     * @param shopId The unique positive non-zero numeric ID for an Etsy Shop.
     * @param title The name string of this shipping profile.
     * @param originCountryIso The ISO code of the country from which the listing ships.
     * @param primaryCost The cost of shipping to this country/region alone, measured in the store&#39;s default currency.
     * @param secondaryCost The cost of shipping to this country/region with another item, measured in the store&#39;s default currency.
     * @param minProcessingTime The minimum time required to process to ship listings with this shipping profile.
     * @param maxProcessingTime The maximum processing time the listing needs to ship.
     * @param processingTimeUnit The unit used to represent how long a processing time is. A week is equivalent to the set processing schedule (default to 5 business days). If none is provided, the unit is set to \\\&quot;business_days\\\&quot;. (optional, default to business_days)
     * @param destinationCountryIso The ISO code of the country to which the listing ships. If null, request sets destination to destination_region. Required if destination_region is null or not provided. (optional)
     * @param destinationRegion The code of the region to which the listing ships. A region represents a set of countries. Supported regions are Europe Union and Non-Europe Union (countries in Europe not in EU). If &#x60;none&#x60;, request sets destination to destination_country_iso. Required if destination_country_iso is null or not provided. (optional, default to none)
     * @param originPostalCode The postal code string (not necessarily a number) for the location from which the listing ships. Required if the &#x60;origin_country_iso&#x60; supports postal codes. See the [Fulfillment Tutorial docs](https://developer.etsy.com/documentation/tutorials/fulfillment/#countries-requiring-postal-codes) for more info (optional, default to "")
     * @param shippingCarrierId The unique ID of a supported shipping carrier, which is used to calculate an Estimated Delivery Date. **Required with &#x60;mail_class&#x60;** if &#x60;min_delivery_days&#x60; and &#x60;max_delivery_days&#x60; are null. (optional, default to 0)
     * @param mailClass The unique ID string of a shipping carrier&#39;s mail class, which is used to calculate an estimated delivery date. **Required with &#x60;shipping_carrier_id&#x60;** if &#x60;min_delivery_days&#x60; and &#x60;max_delivery_days&#x60; are null. (optional)
     * @param minDeliveryDays The minimum number of business days a buyer can expect to wait to receive their purchased item once it has shipped. **Required with &#x60;max_delivery_days&#x60;** if &#x60;mail_class&#x60; is null. (optional)
     * @param maxDeliveryDays The maximum number of business days a buyer can expect to wait to receive their purchased item once it has shipped. **Required with &#x60;min_delivery_days&#x60;** if &#x60;mail_class&#x60; is null. (optional)
     * @return ShopShippingProfile
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun createShopShippingProfile(shopId: kotlin.Long, title: kotlin.String, originCountryIso: kotlin.String, primaryCost: kotlin.Float, secondaryCost: kotlin.Float, minProcessingTime: kotlin.Int, maxProcessingTime: kotlin.Int, processingTimeUnit: ProcessingTimeUnitCreateShopShippingProfile? = ProcessingTimeUnitCreateShopShippingProfile.business_days, destinationCountryIso: kotlin.String? = null, destinationRegion: DestinationRegionCreateShopShippingProfile? = DestinationRegionCreateShopShippingProfile.none, originPostalCode: kotlin.String? = "", shippingCarrierId: kotlin.Int? = 0, mailClass: kotlin.String? = null, minDeliveryDays: kotlin.Int? = null, maxDeliveryDays: kotlin.Int? = null): HttpResponse<ShopShippingProfile> {

        val localVariableAuthNames = listOf<String>("api_key", "oauth2")

        val localVariableBody = 
            ParametersBuilder().also {
                title?.apply { it.append("title", title.toString()) }
                originCountryIso?.apply { it.append("origin_country_iso", originCountryIso.toString()) }
                primaryCost?.apply { it.append("primary_cost", primaryCost.toString()) }
                secondaryCost?.apply { it.append("secondary_cost", secondaryCost.toString()) }
                minProcessingTime?.apply { it.append("min_processing_time", minProcessingTime.toString()) }
                maxProcessingTime?.apply { it.append("max_processing_time", maxProcessingTime.toString()) }
                processingTimeUnit?.apply { it.append("processing_time_unit", processingTimeUnit.toString()) }
                destinationCountryIso?.apply { it.append("destination_country_iso", destinationCountryIso.toString()) }
                destinationRegion?.apply { it.append("destination_region", destinationRegion.toString()) }
                originPostalCode?.apply { it.append("origin_postal_code", originPostalCode.toString()) }
                shippingCarrierId?.apply { it.append("shipping_carrier_id", shippingCarrierId.toString()) }
                mailClass?.apply { it.append("mail_class", mailClass.toString()) }
                minDeliveryDays?.apply { it.append("min_delivery_days", minDeliveryDays.toString()) }
                maxDeliveryDays?.apply { it.append("max_delivery_days", maxDeliveryDays.toString()) }
            }.build()

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/v3/application/shops/{shop_id}/shipping-profiles".replace("{" + "shop_id" + "}", "$shopId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return urlEncodedFormRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



    /**
     * enum for parameter destinationRegion
     */
    @Serializable
    enum class DestinationRegionCreateShopShippingProfileDestination(val value: kotlin.String) {
        
        @SerialName(value = "eu")
        eu("eu"),
        
        @SerialName(value = "non_eu")
        non_eu("non_eu"),
        
        @SerialName(value = "none")
        none("none")
        
    }

    /**
     * 
     * &lt;div class&#x3D;\&quot;wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\&quot;&gt;&lt;span class&#x3D;\&quot;wt-badge wt-badge--notificationPrimary wt-bg-slime-tint wt-mr-xs-2\&quot;&gt;General Release&lt;/span&gt;&lt;a class&#x3D;\&quot;wt-text-link\&quot; href&#x3D;\&quot;https://github.com/etsy/open-api/discussions\&quot; target&#x3D;\&quot;_blank\&quot; rel&#x3D;\&quot;noopener noreferrer\&quot;&gt;Report bug&lt;/a&gt;&lt;/div&gt;&lt;div class&#x3D;\&quot;wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\&quot;&gt;&lt;p class&#x3D;\&quot;wt-text-body-01 banner-text\&quot;&gt;This endpoint is ready for production use.&lt;/p&gt;&lt;/div&gt;  Creates a new shipping destination, which sets the shipping cost, carrier, and class for a destination in a [shipping profile](/documentation/reference/#tag/Shop-ShippingProfile). createShopShippingProfileDestination assigns costs using the currency of the associated shop. Set the destination using either &#x60;destination_country_iso&#x60; or &#x60;destination_region&#x60;; &#x60;destination_country_iso&#x60; and &#x60;destination_region&#x60; are mutually exclusive — set one or the other. Setting both triggers error 400. If the request sets neither &#x60;destination_country_iso&#x60; nor &#x60;destination_region&#x60;, the default destination is \&quot;everywhere\&quot;. You must also either assign both a &#x60;shipping_carrier_id&#x60; AND &#x60;mail_class&#x60; or both &#x60;min_delivery_days&#x60; AND &#x60;max_delivery_days&#x60;.
     * @param shopId The unique positive non-zero numeric ID for an Etsy Shop.
     * @param shippingProfileId The numeric ID of the [shipping profile](/documentation/reference#operation/getShopShippingProfile) associated with the listing. Required when listing type is &#x60;physical&#x60;.
     * @param primaryCost The cost of shipping to this country/region alone, measured in the store&#39;s default currency.
     * @param secondaryCost The cost of shipping to this country/region with another item, measured in the store&#39;s default currency.
     * @param destinationCountryIso The ISO code of the country to which the listing ships. If null, request sets destination to destination_region. Required if destination_region is null or not provided. (optional)
     * @param destinationRegion The code of the region to which the listing ships. A region represents a set of countries. Supported regions are Europe Union and Non-Europe Union (countries in Europe not in EU). If &#x60;none&#x60;, request sets destination to destination_country_iso. Required if destination_country_iso is null or not provided. (optional, default to none)
     * @param shippingCarrierId The unique ID of a supported shipping carrier, which is used to calculate an Estimated Delivery Date. **Required with &#x60;mail_class&#x60;** if &#x60;min_delivery_days&#x60; and &#x60;max_delivery_days&#x60; are null. (optional, default to 0)
     * @param mailClass The unique ID string of a shipping carrier&#39;s mail class, which is used to calculate an estimated delivery date. **Required with &#x60;shipping_carrier_id&#x60;** if &#x60;min_delivery_days&#x60; and &#x60;max_delivery_days&#x60; are null. (optional)
     * @param minDeliveryDays The minimum number of business days a buyer can expect to wait to receive their purchased item once it has shipped. **Required with &#x60;max_delivery_days&#x60;** if &#x60;mail_class&#x60; is null. (optional)
     * @param maxDeliveryDays The maximum number of business days a buyer can expect to wait to receive their purchased item once it has shipped. **Required with &#x60;min_delivery_days&#x60;** if &#x60;mail_class&#x60; is null. (optional)
     * @return ShopShippingProfileDestination
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun createShopShippingProfileDestination(shopId: kotlin.Long, shippingProfileId: kotlin.Long, primaryCost: kotlin.Float, secondaryCost: kotlin.Float, destinationCountryIso: kotlin.String? = null, destinationRegion: DestinationRegionCreateShopShippingProfileDestination? = DestinationRegionCreateShopShippingProfileDestination.none, shippingCarrierId: kotlin.Int? = 0, mailClass: kotlin.String? = null, minDeliveryDays: kotlin.Int? = null, maxDeliveryDays: kotlin.Int? = null): HttpResponse<ShopShippingProfileDestination> {

        val localVariableAuthNames = listOf<String>("api_key", "oauth2")

        val localVariableBody = 
            ParametersBuilder().also {
                primaryCost?.apply { it.append("primary_cost", primaryCost.toString()) }
                secondaryCost?.apply { it.append("secondary_cost", secondaryCost.toString()) }
                destinationCountryIso?.apply { it.append("destination_country_iso", destinationCountryIso.toString()) }
                destinationRegion?.apply { it.append("destination_region", destinationRegion.toString()) }
                shippingCarrierId?.apply { it.append("shipping_carrier_id", shippingCarrierId.toString()) }
                mailClass?.apply { it.append("mail_class", mailClass.toString()) }
                minDeliveryDays?.apply { it.append("min_delivery_days", minDeliveryDays.toString()) }
                maxDeliveryDays?.apply { it.append("max_delivery_days", maxDeliveryDays.toString()) }
            }.build()

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/v3/application/shops/{shop_id}/shipping-profiles/{shipping_profile_id}/destinations".replace("{" + "shop_id" + "}", "$shopId").replace("{" + "shipping_profile_id" + "}", "$shippingProfileId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return urlEncodedFormRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



    /**
     * enum for parameter type
     */
    @Serializable
    enum class TypeCreateShopShippingProfileUpgrade(val value: kotlin.String) {
        
        @SerialName(value = "0")
        _0("0"),
        
        @SerialName(value = "1")
        _1("1")
        
    }

    /**
     * 
     * &lt;div class&#x3D;\&quot;wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\&quot;&gt;&lt;span class&#x3D;\&quot;wt-badge wt-badge--notificationPrimary wt-bg-slime-tint wt-mr-xs-2\&quot;&gt;General Release&lt;/span&gt;&lt;a class&#x3D;\&quot;wt-text-link\&quot; href&#x3D;\&quot;https://github.com/etsy/open-api/discussions\&quot; target&#x3D;\&quot;_blank\&quot; rel&#x3D;\&quot;noopener noreferrer\&quot;&gt;Report bug&lt;/a&gt;&lt;/div&gt;&lt;div class&#x3D;\&quot;wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\&quot;&gt;&lt;p class&#x3D;\&quot;wt-text-body-01 banner-text\&quot;&gt;This endpoint is ready for production use.&lt;/p&gt;&lt;/div&gt;  Creates a new shipping profile upgrade, which can establish a price for a shipping option, such as an alternate carrier or faster delivery.
     * @param shopId The unique positive non-zero numeric ID for an Etsy Shop.
     * @param shippingProfileId The numeric ID of the [shipping profile](/documentation/reference#operation/getShopShippingProfile) associated with the listing. Required when listing type is &#x60;physical&#x60;.
     * @param type The type of the shipping upgrade. Domestic (0) or international (1).
     * @param upgradeName Name for the shipping upgrade shown to shoppers at checkout, e.g. USPS Priority.
     * @param price Additional cost of adding the shipping upgrade.
     * @param secondaryPrice Additional cost of adding the shipping upgrade for each additional item.
     * @param shippingCarrierId The unique ID of a supported shipping carrier, which is used to calculate an Estimated Delivery Date. **Required with &#x60;mail_class&#x60;** if &#x60;min_delivery_days&#x60; and &#x60;max_delivery_days&#x60; are null. (optional, default to 0)
     * @param mailClass The unique ID string of a shipping carrier&#39;s mail class, which is used to calculate an estimated delivery date. **Required with &#x60;shipping_carrier_id&#x60;** if &#x60;min_delivery_days&#x60; and &#x60;max_delivery_days&#x60; are null. (optional)
     * @param minDeliveryDays The minimum number of business days a buyer can expect to wait to receive their purchased item once it has shipped. **Required with &#x60;max_delivery_days&#x60;** if &#x60;mail_class&#x60; is null. (optional)
     * @param maxDeliveryDays The maximum number of business days a buyer can expect to wait to receive their purchased item once it has shipped. **Required with &#x60;min_delivery_days&#x60;** if &#x60;mail_class&#x60; is null. (optional)
     * @return ShopShippingProfileUpgrade
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun createShopShippingProfileUpgrade(shopId: kotlin.Long, shippingProfileId: kotlin.Long, type: TypeCreateShopShippingProfileUpgrade, upgradeName: kotlin.String, price: kotlin.Float, secondaryPrice: kotlin.Float, shippingCarrierId: kotlin.Int? = 0, mailClass: kotlin.String? = null, minDeliveryDays: kotlin.Int? = null, maxDeliveryDays: kotlin.Int? = null): HttpResponse<ShopShippingProfileUpgrade> {

        val localVariableAuthNames = listOf<String>("api_key", "oauth2")

        val localVariableBody = 
            ParametersBuilder().also {
                type?.apply { it.append("type", type.toString()) }
                upgradeName?.apply { it.append("upgrade_name", upgradeName.toString()) }
                price?.apply { it.append("price", price.toString()) }
                secondaryPrice?.apply { it.append("secondary_price", secondaryPrice.toString()) }
                shippingCarrierId?.apply { it.append("shipping_carrier_id", shippingCarrierId.toString()) }
                mailClass?.apply { it.append("mail_class", mailClass.toString()) }
                minDeliveryDays?.apply { it.append("min_delivery_days", minDeliveryDays.toString()) }
                maxDeliveryDays?.apply { it.append("max_delivery_days", maxDeliveryDays.toString()) }
            }.build()

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/v3/application/shops/{shop_id}/shipping-profiles/{shipping_profile_id}/upgrades".replace("{" + "shop_id" + "}", "$shopId").replace("{" + "shipping_profile_id" + "}", "$shippingProfileId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return urlEncodedFormRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * 
     * &lt;div class&#x3D;\&quot;wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\&quot;&gt;&lt;span class&#x3D;\&quot;wt-badge wt-badge--notificationPrimary wt-bg-slime-tint wt-mr-xs-2\&quot;&gt;General Release&lt;/span&gt;&lt;a class&#x3D;\&quot;wt-text-link\&quot; href&#x3D;\&quot;https://github.com/etsy/open-api/discussions\&quot; target&#x3D;\&quot;_blank\&quot; rel&#x3D;\&quot;noopener noreferrer\&quot;&gt;Report bug&lt;/a&gt;&lt;/div&gt;&lt;div class&#x3D;\&quot;wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\&quot;&gt;&lt;p class&#x3D;\&quot;wt-text-body-01 banner-text\&quot;&gt;This endpoint is ready for production use.&lt;/p&gt;&lt;/div&gt;  Deletes a ShippingProfile by given id.
     * @param shopId The unique positive non-zero numeric ID for an Etsy Shop.
     * @param shippingProfileId The numeric ID of the [shipping profile](/documentation/reference#operation/getShopShippingProfile) associated with the listing. Required when listing type is &#x60;physical&#x60;.
     * @return void
     */
    open suspend fun deleteShopShippingProfile(shopId: kotlin.Long, shippingProfileId: kotlin.Long): HttpResponse<Unit> {

        val localVariableAuthNames = listOf<String>("api_key", "oauth2")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.DELETE,
            "/v3/application/shops/{shop_id}/shipping-profiles/{shipping_profile_id}".replace("{" + "shop_id" + "}", "$shopId").replace("{" + "shipping_profile_id" + "}", "$shippingProfileId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * 
     * &lt;div class&#x3D;\&quot;wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\&quot;&gt;&lt;span class&#x3D;\&quot;wt-badge wt-badge--notificationPrimary wt-bg-slime-tint wt-mr-xs-2\&quot;&gt;General Release&lt;/span&gt;&lt;a class&#x3D;\&quot;wt-text-link\&quot; href&#x3D;\&quot;https://github.com/etsy/open-api/discussions\&quot; target&#x3D;\&quot;_blank\&quot; rel&#x3D;\&quot;noopener noreferrer\&quot;&gt;Report bug&lt;/a&gt;&lt;/div&gt;&lt;div class&#x3D;\&quot;wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\&quot;&gt;&lt;p class&#x3D;\&quot;wt-text-body-01 banner-text\&quot;&gt;This endpoint is ready for production use.&lt;/p&gt;&lt;/div&gt;  Deletes a shipping destination and removes the destination option from every listing that uses the associated shipping profile. A shipping profile requires at least one shipping destination, so this endpoint cannot delete the final shipping destination for any shipping profile. To delete the final shipping destination from a shipping profile, you must [delete the entire shipping profile](/documentation/reference/#operation/deleteShopShippingProfile).
     * @param shopId The unique positive non-zero numeric ID for an Etsy Shop.
     * @param shippingProfileId The numeric ID of the [shipping profile](/documentation/reference#operation/getShopShippingProfile) associated with the listing. Required when listing type is &#x60;physical&#x60;.
     * @param shippingProfileDestinationId The numeric ID of the shipping profile destination in the [shipping profile](/documentation/reference#tag/Shop-ShippingProfile) associated with the listing.
     * @return void
     */
    open suspend fun deleteShopShippingProfileDestination(shopId: kotlin.Long, shippingProfileId: kotlin.Long, shippingProfileDestinationId: kotlin.Long): HttpResponse<Unit> {

        val localVariableAuthNames = listOf<String>("api_key", "oauth2")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.DELETE,
            "/v3/application/shops/{shop_id}/shipping-profiles/{shipping_profile_id}/destinations/{shipping_profile_destination_id}".replace("{" + "shop_id" + "}", "$shopId").replace("{" + "shipping_profile_id" + "}", "$shippingProfileId").replace("{" + "shipping_profile_destination_id" + "}", "$shippingProfileDestinationId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * 
     * &lt;div class&#x3D;\&quot;wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\&quot;&gt;&lt;span class&#x3D;\&quot;wt-badge wt-badge--notificationPrimary wt-bg-slime-tint wt-mr-xs-2\&quot;&gt;General Release&lt;/span&gt;&lt;a class&#x3D;\&quot;wt-text-link\&quot; href&#x3D;\&quot;https://github.com/etsy/open-api/discussions\&quot; target&#x3D;\&quot;_blank\&quot; rel&#x3D;\&quot;noopener noreferrer\&quot;&gt;Report bug&lt;/a&gt;&lt;/div&gt;&lt;div class&#x3D;\&quot;wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\&quot;&gt;&lt;p class&#x3D;\&quot;wt-text-body-01 banner-text\&quot;&gt;This endpoint is ready for production use.&lt;/p&gt;&lt;/div&gt;  Deletes a shipping profile upgrade and removes the upgrade option from every listing that uses the associated shipping profile.
     * @param shopId The unique positive non-zero numeric ID for an Etsy Shop.
     * @param shippingProfileId The numeric ID of the shipping profile.
     * @param upgradeId The numeric ID that is associated with a shipping upgrade
     * @return void
     */
    open suspend fun deleteShopShippingProfileUpgrade(shopId: kotlin.Long, shippingProfileId: kotlin.Long, upgradeId: kotlin.Long): HttpResponse<Unit> {

        val localVariableAuthNames = listOf<String>("api_key", "oauth2")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.DELETE,
            "/v3/application/shops/{shop_id}/shipping-profiles/{shipping_profile_id}/upgrades/{upgrade_id}".replace("{" + "shop_id" + "}", "$shopId").replace("{" + "shipping_profile_id" + "}", "$shippingProfileId").replace("{" + "upgrade_id" + "}", "$upgradeId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * 
     * &lt;div class&#x3D;\&quot;wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\&quot;&gt;&lt;span class&#x3D;\&quot;wt-badge wt-badge--notificationPrimary wt-bg-slime-tint wt-mr-xs-2\&quot;&gt;General Release&lt;/span&gt;&lt;a class&#x3D;\&quot;wt-text-link\&quot; href&#x3D;\&quot;https://github.com/etsy/open-api/discussions\&quot; target&#x3D;\&quot;_blank\&quot; rel&#x3D;\&quot;noopener noreferrer\&quot;&gt;Report bug&lt;/a&gt;&lt;/div&gt;&lt;div class&#x3D;\&quot;wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\&quot;&gt;&lt;p class&#x3D;\&quot;wt-text-body-01 banner-text\&quot;&gt;This endpoint is ready for production use.&lt;/p&gt;&lt;/div&gt;  Retrieves a list of available shipping carriers and the mail classes associated with them for a given country
     * @param originCountryIso The ISO code of the country from which the listing ships.
     * @return ShippingCarriers
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun getShippingCarriers(originCountryIso: kotlin.String): HttpResponse<ShippingCarriers> {

        val localVariableAuthNames = listOf<String>("api_key")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        originCountryIso?.apply { localVariableQuery["origin_country_iso"] = listOf("$originCountryIso") }
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/v3/application/shipping-carriers",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * 
     * &lt;div class&#x3D;\&quot;wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\&quot;&gt;&lt;span class&#x3D;\&quot;wt-badge wt-badge--notificationPrimary wt-bg-slime-tint wt-mr-xs-2\&quot;&gt;General Release&lt;/span&gt;&lt;a class&#x3D;\&quot;wt-text-link\&quot; href&#x3D;\&quot;https://github.com/etsy/open-api/discussions\&quot; target&#x3D;\&quot;_blank\&quot; rel&#x3D;\&quot;noopener noreferrer\&quot;&gt;Report bug&lt;/a&gt;&lt;/div&gt;&lt;div class&#x3D;\&quot;wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\&quot;&gt;&lt;p class&#x3D;\&quot;wt-text-body-01 banner-text\&quot;&gt;This endpoint is ready for production use.&lt;/p&gt;&lt;/div&gt;  Retrieves a Shipping Profile referenced by shipping profile ID.
     * @param shopId The unique positive non-zero numeric ID for an Etsy Shop.
     * @param shippingProfileId The numeric ID of the [shipping profile](/documentation/reference#operation/getShopShippingProfile) associated with the listing. Required when listing type is &#x60;physical&#x60;.
     * @return ShopShippingProfile
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun getShopShippingProfile(shopId: kotlin.Long, shippingProfileId: kotlin.Long): HttpResponse<ShopShippingProfile> {

        val localVariableAuthNames = listOf<String>("api_key", "oauth2")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/v3/application/shops/{shop_id}/shipping-profiles/{shipping_profile_id}".replace("{" + "shop_id" + "}", "$shopId").replace("{" + "shipping_profile_id" + "}", "$shippingProfileId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * 
     * &lt;div class&#x3D;\&quot;wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\&quot;&gt;&lt;span class&#x3D;\&quot;wt-badge wt-badge--notificationPrimary wt-bg-slime-tint wt-mr-xs-2\&quot;&gt;General Release&lt;/span&gt;&lt;a class&#x3D;\&quot;wt-text-link\&quot; href&#x3D;\&quot;https://github.com/etsy/open-api/discussions\&quot; target&#x3D;\&quot;_blank\&quot; rel&#x3D;\&quot;noopener noreferrer\&quot;&gt;Report bug&lt;/a&gt;&lt;/div&gt;&lt;div class&#x3D;\&quot;wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\&quot;&gt;&lt;p class&#x3D;\&quot;wt-text-body-01 banner-text\&quot;&gt;This endpoint is ready for production use.&lt;/p&gt;&lt;/div&gt;  Retrieves a list of shipping destination objects associated with a shipping profile.
     * @param shopId The unique positive non-zero numeric ID for an Etsy Shop.
     * @param shippingProfileId The numeric ID of the [shipping profile](/documentation/reference#operation/getShopShippingProfile) associated with the listing. Required when listing type is &#x60;physical&#x60;.
     * @param limit The maximum number of results to return. (optional, default to 25)
     * @param offset The number of records to skip before selecting the first result. (optional, default to 0)
     * @return ShopShippingProfileDestinations
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun getShopShippingProfileDestinationsByShippingProfile(shopId: kotlin.Long, shippingProfileId: kotlin.Long, limit: kotlin.Int? = 25, offset: kotlin.Int? = 0): HttpResponse<ShopShippingProfileDestinations> {

        val localVariableAuthNames = listOf<String>("api_key", "oauth2")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        limit?.apply { localVariableQuery["limit"] = listOf("$limit") }
        offset?.apply { localVariableQuery["offset"] = listOf("$offset") }
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/v3/application/shops/{shop_id}/shipping-profiles/{shipping_profile_id}/destinations".replace("{" + "shop_id" + "}", "$shopId").replace("{" + "shipping_profile_id" + "}", "$shippingProfileId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * 
     * &lt;div class&#x3D;\&quot;wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\&quot;&gt;&lt;span class&#x3D;\&quot;wt-badge wt-badge--notificationPrimary wt-bg-slime-tint wt-mr-xs-2\&quot;&gt;General Release&lt;/span&gt;&lt;a class&#x3D;\&quot;wt-text-link\&quot; href&#x3D;\&quot;https://github.com/etsy/open-api/discussions\&quot; target&#x3D;\&quot;_blank\&quot; rel&#x3D;\&quot;noopener noreferrer\&quot;&gt;Report bug&lt;/a&gt;&lt;/div&gt;&lt;div class&#x3D;\&quot;wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\&quot;&gt;&lt;p class&#x3D;\&quot;wt-text-body-01 banner-text\&quot;&gt;This endpoint is ready for production use.&lt;/p&gt;&lt;/div&gt;  Retrieves the list of shipping profile upgrades assigned to a specific shipping profile.
     * @param shopId The unique positive non-zero numeric ID for an Etsy Shop.
     * @param shippingProfileId The numeric ID of the [shipping profile](/documentation/reference#operation/getShopShippingProfile) associated with the listing. Required when listing type is &#x60;physical&#x60;.
     * @return ShopShippingProfileUpgrades
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun getShopShippingProfileUpgrades(shopId: kotlin.Long, shippingProfileId: kotlin.Long): HttpResponse<ShopShippingProfileUpgrades> {

        val localVariableAuthNames = listOf<String>("api_key", "oauth2")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/v3/application/shops/{shop_id}/shipping-profiles/{shipping_profile_id}/upgrades".replace("{" + "shop_id" + "}", "$shopId").replace("{" + "shipping_profile_id" + "}", "$shippingProfileId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * 
     * &lt;div class&#x3D;\&quot;wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\&quot;&gt;&lt;span class&#x3D;\&quot;wt-badge wt-badge--notificationPrimary wt-bg-slime-tint wt-mr-xs-2\&quot;&gt;General Release&lt;/span&gt;&lt;a class&#x3D;\&quot;wt-text-link\&quot; href&#x3D;\&quot;https://github.com/etsy/open-api/discussions\&quot; target&#x3D;\&quot;_blank\&quot; rel&#x3D;\&quot;noopener noreferrer\&quot;&gt;Report bug&lt;/a&gt;&lt;/div&gt;&lt;div class&#x3D;\&quot;wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\&quot;&gt;&lt;p class&#x3D;\&quot;wt-text-body-01 banner-text\&quot;&gt;This endpoint is ready for production use.&lt;/p&gt;&lt;/div&gt;  Retrieves a list of shipping profiles available in the specific Etsy shop identified by its shop ID.
     * @param shopId The unique positive non-zero numeric ID for an Etsy Shop.
     * @return ShopShippingProfiles
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun getShopShippingProfiles(shopId: kotlin.Long): HttpResponse<ShopShippingProfiles> {

        val localVariableAuthNames = listOf<String>("api_key", "oauth2")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/v3/application/shops/{shop_id}/shipping-profiles".replace("{" + "shop_id" + "}", "$shopId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



    /**
     * enum for parameter processingTimeUnit
     */
    @Serializable
    enum class ProcessingTimeUnitUpdateShopShippingProfile(val value: kotlin.String) {
        
        @SerialName(value = "business_days")
        business_days("business_days"),
        
        @SerialName(value = "weeks")
        weeks("weeks")
        
    }

    /**
     * 
     * &lt;div class&#x3D;\&quot;wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\&quot;&gt;&lt;span class&#x3D;\&quot;wt-badge wt-badge--notificationPrimary wt-bg-slime-tint wt-mr-xs-2\&quot;&gt;General Release&lt;/span&gt;&lt;a class&#x3D;\&quot;wt-text-link\&quot; href&#x3D;\&quot;https://github.com/etsy/open-api/discussions\&quot; target&#x3D;\&quot;_blank\&quot; rel&#x3D;\&quot;noopener noreferrer\&quot;&gt;Report bug&lt;/a&gt;&lt;/div&gt;&lt;div class&#x3D;\&quot;wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\&quot;&gt;&lt;p class&#x3D;\&quot;wt-text-body-01 banner-text\&quot;&gt;This endpoint is ready for production use.&lt;/p&gt;&lt;/div&gt;  Changes the settings in a shipping profile. You can pass a country iso code or a region when updating a ShippingProfile, but not both. Only one is required. You must pass either a shipping_carrier_id AND mail_class, or both min and max_delivery_days.
     * @param shopId The unique positive non-zero numeric ID for an Etsy Shop.
     * @param shippingProfileId The numeric ID of the [shipping profile](/documentation/reference#operation/getShopShippingProfile) associated with the listing. Required when listing type is &#x60;physical&#x60;.
     * @param title The name string of this shipping profile. (optional)
     * @param originCountryIso The ISO code of the country from which the listing ships. (optional)
     * @param minProcessingTime The minimum time required to process to ship listings with this shipping profile. (optional)
     * @param maxProcessingTime The maximum processing time the listing needs to ship. (optional)
     * @param processingTimeUnit The unit used to represent how long a processing time is. A week is equivalent to the set processing schedule (default to 5 business days). If none is provided, the unit is set to \\\&quot;business_days\\\&quot;. (optional, default to business_days)
     * @param originPostalCode The postal code string (not necessarily a number) for the location from which the listing ships. Required if the &#x60;origin_country_iso&#x60; supports postal codes. See the [Fulfillment Tutorial docs](https://developer.etsy.com/documentation/tutorials/fulfillment/#countries-requiring-postal-codes) for more info (optional)
     * @return ShopShippingProfile
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun updateShopShippingProfile(shopId: kotlin.Long, shippingProfileId: kotlin.Long, title: kotlin.String? = null, originCountryIso: kotlin.String? = null, minProcessingTime: kotlin.Int? = null, maxProcessingTime: kotlin.Int? = null, processingTimeUnit: ProcessingTimeUnitUpdateShopShippingProfile? = ProcessingTimeUnitUpdateShopShippingProfile.business_days, originPostalCode: kotlin.String? = null): HttpResponse<ShopShippingProfile> {

        val localVariableAuthNames = listOf<String>("api_key", "oauth2")

        val localVariableBody = 
            ParametersBuilder().also {
                title?.apply { it.append("title", title.toString()) }
                originCountryIso?.apply { it.append("origin_country_iso", originCountryIso.toString()) }
                minProcessingTime?.apply { it.append("min_processing_time", minProcessingTime.toString()) }
                maxProcessingTime?.apply { it.append("max_processing_time", maxProcessingTime.toString()) }
                processingTimeUnit?.apply { it.append("processing_time_unit", processingTimeUnit.toString()) }
                originPostalCode?.apply { it.append("origin_postal_code", originPostalCode.toString()) }
            }.build()

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.PUT,
            "/v3/application/shops/{shop_id}/shipping-profiles/{shipping_profile_id}".replace("{" + "shop_id" + "}", "$shopId").replace("{" + "shipping_profile_id" + "}", "$shippingProfileId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return urlEncodedFormRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



    /**
     * enum for parameter destinationRegion
     */
    @Serializable
    enum class DestinationRegionUpdateShopShippingProfileDestination(val value: kotlin.String) {
        
        @SerialName(value = "eu")
        eu("eu"),
        
        @SerialName(value = "non_eu")
        non_eu("non_eu"),
        
        @SerialName(value = "none")
        none("none")
        
    }

    /**
     * 
     * &lt;div class&#x3D;\&quot;wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\&quot;&gt;&lt;span class&#x3D;\&quot;wt-badge wt-badge--notificationPrimary wt-bg-slime-tint wt-mr-xs-2\&quot;&gt;General Release&lt;/span&gt;&lt;a class&#x3D;\&quot;wt-text-link\&quot; href&#x3D;\&quot;https://github.com/etsy/open-api/discussions\&quot; target&#x3D;\&quot;_blank\&quot; rel&#x3D;\&quot;noopener noreferrer\&quot;&gt;Report bug&lt;/a&gt;&lt;/div&gt;&lt;div class&#x3D;\&quot;wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\&quot;&gt;&lt;p class&#x3D;\&quot;wt-text-body-01 banner-text\&quot;&gt;This endpoint is ready for production use.&lt;/p&gt;&lt;/div&gt;  Updates an existing shipping destination, which can set or reassign the shipping cost, carrier, and class for a destination.
     * @param shopId The unique positive non-zero numeric ID for an Etsy Shop.
     * @param shippingProfileId The numeric ID of the [shipping profile](/documentation/reference#operation/getShopShippingProfile) associated with the listing. Required when listing type is &#x60;physical&#x60;.
     * @param shippingProfileDestinationId The numeric ID of the shipping profile destination in the [shipping profile](/documentation/reference#tag/Shop-ShippingProfile) associated with the listing.
     * @param primaryCost The cost of shipping to this country/region alone, measured in the store&#39;s default currency. (optional)
     * @param secondaryCost The cost of shipping to this country/region with another item, measured in the store&#39;s default currency. (optional)
     * @param destinationCountryIso The ISO code of the country to which the listing ships. If null, request sets destination to destination_region. Required if destination_region is null or not provided. (optional)
     * @param destinationRegion The code of the region to which the listing ships. A region represents a set of countries. Supported regions are Europe Union and Non-Europe Union (countries in Europe not in EU). If &#x60;none&#x60;, request sets destination to destination_country_iso. Required if destination_country_iso is null or not provided. (optional, default to none)
     * @param shippingCarrierId The unique ID of a supported shipping carrier, which is used to calculate an Estimated Delivery Date. **Required with &#x60;mail_class&#x60;** if &#x60;min_delivery_days&#x60; and &#x60;max_delivery_days&#x60; are null. (optional)
     * @param mailClass The unique ID string of a shipping carrier&#39;s mail class, which is used to calculate an estimated delivery date. **Required with &#x60;shipping_carrier_id&#x60;** if &#x60;min_delivery_days&#x60; and &#x60;max_delivery_days&#x60; are null. (optional)
     * @param minDeliveryDays The minimum number of business days a buyer can expect to wait to receive their purchased item once it has shipped. **Required with &#x60;max_delivery_days&#x60;** if &#x60;mail_class&#x60; is null. (optional)
     * @param maxDeliveryDays The maximum number of business days a buyer can expect to wait to receive their purchased item once it has shipped. **Required with &#x60;min_delivery_days&#x60;** if &#x60;mail_class&#x60; is null. (optional)
     * @return ShopShippingProfileDestination
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun updateShopShippingProfileDestination(shopId: kotlin.Long, shippingProfileId: kotlin.Long, shippingProfileDestinationId: kotlin.Long, primaryCost: kotlin.Float? = null, secondaryCost: kotlin.Float? = null, destinationCountryIso: kotlin.String? = null, destinationRegion: DestinationRegionUpdateShopShippingProfileDestination? = DestinationRegionUpdateShopShippingProfileDestination.none, shippingCarrierId: kotlin.Int? = null, mailClass: kotlin.String? = null, minDeliveryDays: kotlin.Int? = null, maxDeliveryDays: kotlin.Int? = null): HttpResponse<ShopShippingProfileDestination> {

        val localVariableAuthNames = listOf<String>("api_key", "oauth2")

        val localVariableBody = 
            ParametersBuilder().also {
                primaryCost?.apply { it.append("primary_cost", primaryCost.toString()) }
                secondaryCost?.apply { it.append("secondary_cost", secondaryCost.toString()) }
                destinationCountryIso?.apply { it.append("destination_country_iso", destinationCountryIso.toString()) }
                destinationRegion?.apply { it.append("destination_region", destinationRegion.toString()) }
                shippingCarrierId?.apply { it.append("shipping_carrier_id", shippingCarrierId.toString()) }
                mailClass?.apply { it.append("mail_class", mailClass.toString()) }
                minDeliveryDays?.apply { it.append("min_delivery_days", minDeliveryDays.toString()) }
                maxDeliveryDays?.apply { it.append("max_delivery_days", maxDeliveryDays.toString()) }
            }.build()

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.PUT,
            "/v3/application/shops/{shop_id}/shipping-profiles/{shipping_profile_id}/destinations/{shipping_profile_destination_id}".replace("{" + "shop_id" + "}", "$shopId").replace("{" + "shipping_profile_id" + "}", "$shippingProfileId").replace("{" + "shipping_profile_destination_id" + "}", "$shippingProfileDestinationId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return urlEncodedFormRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



    /**
     * enum for parameter type
     */
    @Serializable
    enum class TypeUpdateShopShippingProfileUpgrade(val value: kotlin.String) {
        
        @SerialName(value = "0")
        _0("0"),
        
        @SerialName(value = "1")
        _1("1")
        
    }

    /**
     * 
     * &lt;div class&#x3D;\&quot;wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\&quot;&gt;&lt;span class&#x3D;\&quot;wt-badge wt-badge--notificationPrimary wt-bg-slime-tint wt-mr-xs-2\&quot;&gt;General Release&lt;/span&gt;&lt;a class&#x3D;\&quot;wt-text-link\&quot; href&#x3D;\&quot;https://github.com/etsy/open-api/discussions\&quot; target&#x3D;\&quot;_blank\&quot; rel&#x3D;\&quot;noopener noreferrer\&quot;&gt;Report bug&lt;/a&gt;&lt;/div&gt;&lt;div class&#x3D;\&quot;wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3\&quot;&gt;&lt;p class&#x3D;\&quot;wt-text-body-01 banner-text\&quot;&gt;This endpoint is ready for production use.&lt;/p&gt;&lt;/div&gt;  Updates a shipping profile upgrade and updates any listings that use the shipping profile.
     * @param shopId The unique positive non-zero numeric ID for an Etsy Shop.
     * @param shippingProfileId The numeric ID of the [shipping profile](/documentation/reference#operation/getShopShippingProfile) associated with the listing. Required when listing type is &#x60;physical&#x60;.
     * @param upgradeId The numeric ID that is associated with a shipping upgrade
     * @param upgradeName Name for the shipping upgrade shown to shoppers at checkout, e.g. USPS Priority. (optional)
     * @param type The type of the shipping upgrade. Domestic (0) or international (1). (optional)
     * @param price Additional cost of adding the shipping upgrade. (optional)
     * @param secondaryPrice Additional cost of adding the shipping upgrade for each additional item. (optional)
     * @param shippingCarrierId The unique ID of a supported shipping carrier, which is used to calculate an Estimated Delivery Date. **Required with &#x60;mail_class&#x60;** if &#x60;min_delivery_days&#x60; and &#x60;max_delivery_days&#x60; are null. (optional)
     * @param mailClass The unique ID string of a shipping carrier&#39;s mail class, which is used to calculate an estimated delivery date. **Required with &#x60;shipping_carrier_id&#x60;** if &#x60;min_delivery_days&#x60; and &#x60;max_delivery_days&#x60; are null. (optional)
     * @param minDeliveryDays The minimum number of business days a buyer can expect to wait to receive their purchased item once it has shipped. **Required with &#x60;max_delivery_days&#x60;** if &#x60;mail_class&#x60; is null. (optional)
     * @param maxDeliveryDays The maximum number of business days a buyer can expect to wait to receive their purchased item once it has shipped. **Required with &#x60;min_delivery_days&#x60;** if &#x60;mail_class&#x60; is null. (optional)
     * @return ShopShippingProfileUpgrade
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun updateShopShippingProfileUpgrade(shopId: kotlin.Long, shippingProfileId: kotlin.Long, upgradeId: kotlin.Long, upgradeName: kotlin.String? = null, type: TypeUpdateShopShippingProfileUpgrade? = null, price: kotlin.Float? = null, secondaryPrice: kotlin.Float? = null, shippingCarrierId: kotlin.Int? = null, mailClass: kotlin.String? = null, minDeliveryDays: kotlin.Int? = null, maxDeliveryDays: kotlin.Int? = null): HttpResponse<ShopShippingProfileUpgrade> {

        val localVariableAuthNames = listOf<String>("api_key", "oauth2")

        val localVariableBody = 
            ParametersBuilder().also {
                upgradeName?.apply { it.append("upgrade_name", upgradeName.toString()) }
                type?.apply { it.append("type", type.toString()) }
                price?.apply { it.append("price", price.toString()) }
                secondaryPrice?.apply { it.append("secondary_price", secondaryPrice.toString()) }
                shippingCarrierId?.apply { it.append("shipping_carrier_id", shippingCarrierId.toString()) }
                mailClass?.apply { it.append("mail_class", mailClass.toString()) }
                minDeliveryDays?.apply { it.append("min_delivery_days", minDeliveryDays.toString()) }
                maxDeliveryDays?.apply { it.append("max_delivery_days", maxDeliveryDays.toString()) }
            }.build()

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.PUT,
            "/v3/application/shops/{shop_id}/shipping-profiles/{shipping_profile_id}/upgrades/{upgrade_id}".replace("{" + "shop_id" + "}", "$shopId").replace("{" + "shipping_profile_id" + "}", "$shippingProfileId").replace("{" + "upgrade_id" + "}", "$upgradeId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return urlEncodedFormRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


}
