/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.etsy.models.BuyerTaxonomyPropertyValue

class BuyerTaxonomyPropertyValueTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of BuyerTaxonomyPropertyValue
        //val modelInstance = BuyerTaxonomyPropertyValue()

        // to test the property `valueId` - The numeric ID of this property value.
        should("test valueId") {
            // uncomment below to test the property
            //modelInstance.valueId shouldBe ("TODO")
        }

        // to test the property `name` - The name string of this property value.
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `scaleId` - The numeric scale ID of the scale to which this property value belongs.
        should("test scaleId") {
            // uncomment below to test the property
            //modelInstance.scaleId shouldBe ("TODO")
        }

        // to test the property `equalTo` - A list of numeric property value IDs this property value is equal to (if any).
        should("test equalTo") {
            // uncomment below to test the property
            //modelInstance.equalTo shouldBe ("TODO")
        }

    }
}
