/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.etsy.models.ListingVariationImage

class ListingVariationImageTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ListingVariationImage
        //val modelInstance = ListingVariationImage()

        // to test the property `propertyId` - The numeric ID of the Property.
        should("test propertyId") {
            // uncomment below to test the property
            //modelInstance.propertyId shouldBe ("TODO")
        }

        // to test the property `valueId` - The numeric ID of the Value.
        should("test valueId") {
            // uncomment below to test the property
            //modelInstance.valueId shouldBe ("TODO")
        }

        // to test the property ``value`` - The string value of the property.
        should("test `value`") {
            // uncomment below to test the property
            //modelInstance.`value` shouldBe ("TODO")
        }

        // to test the property `imageId` - The numeric ID of the Image.
        should("test imageId") {
            // uncomment below to test the property
            //modelInstance.imageId shouldBe ("TODO")
        }

    }
}
