/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.etsy.models.ListingTranslations
import com.etsy.models.ListingTranslation

class ListingTranslationsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ListingTranslations
        //val modelInstance = ListingTranslations()

        // to test the property `de`
        should("test de") {
            // uncomment below to test the property
            //modelInstance.de shouldBe ("TODO")
        }

        // to test the property `enGB`
        should("test enGB") {
            // uncomment below to test the property
            //modelInstance.enGB shouldBe ("TODO")
        }

        // to test the property `enIN`
        should("test enIN") {
            // uncomment below to test the property
            //modelInstance.enIN shouldBe ("TODO")
        }

        // to test the property `enUS`
        should("test enUS") {
            // uncomment below to test the property
            //modelInstance.enUS shouldBe ("TODO")
        }

        // to test the property `es`
        should("test es") {
            // uncomment below to test the property
            //modelInstance.es shouldBe ("TODO")
        }

        // to test the property `fr`
        should("test fr") {
            // uncomment below to test the property
            //modelInstance.fr shouldBe ("TODO")
        }

        // to test the property ``it``
        should("test `it`") {
            // uncomment below to test the property
            //modelInstance.`it` shouldBe ("TODO")
        }

        // to test the property `ja`
        should("test ja") {
            // uncomment below to test the property
            //modelInstance.ja shouldBe ("TODO")
        }

        // to test the property `nl`
        should("test nl") {
            // uncomment below to test the property
            //modelInstance.nl shouldBe ("TODO")
        }

        // to test the property `pl`
        should("test pl") {
            // uncomment below to test the property
            //modelInstance.pl shouldBe ("TODO")
        }

        // to test the property `pt`
        should("test pt") {
            // uncomment below to test the property
            //modelInstance.pt shouldBe ("TODO")
        }

        // to test the property `ru`
        should("test ru") {
            // uncomment below to test the property
            //modelInstance.ru shouldBe ("TODO")
        }

    }
}
