/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.etsy.models.ListingInventoryProduct
import com.etsy.models.ListingInventoryProductOffering
import com.etsy.models.ListingPropertyValue

class ListingInventoryProductTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ListingInventoryProduct
        //val modelInstance = ListingInventoryProduct()

        // to test the property `productId` - The numeric ID for a specific [product](/documentation/reference#tag/ShopListing-Product) purchased from a listing.
        should("test productId") {
            // uncomment below to test the property
            //modelInstance.productId shouldBe ("TODO")
        }

        // to test the property `sku` - The SKU string for the product
        should("test sku") {
            // uncomment below to test the property
            //modelInstance.sku shouldBe ("TODO")
        }

        // to test the property `isDeleted` - When true, someone deleted this product.
        should("test isDeleted") {
            // uncomment below to test the property
            //modelInstance.isDeleted shouldBe ("TODO")
        }

        // to test the property `offerings` - A list of product offering entries for this product.
        should("test offerings") {
            // uncomment below to test the property
            //modelInstance.offerings shouldBe ("TODO")
        }

        // to test the property `propertyValues` - A list of property value entries for this product. Note: parenthesis characters (`(` and `)`) are not allowed.
        should("test propertyValues") {
            // uncomment below to test the property
            //modelInstance.propertyValues shouldBe ("TODO")
        }

    }
}
