/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.etsy.models.ListingInventoryProductOffering
import com.etsy.models.Money

class ListingInventoryProductOfferingTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ListingInventoryProductOffering
        //val modelInstance = ListingInventoryProductOffering()

        // to test the property `offeringId` - The ID for the ProductOffering
        should("test offeringId") {
            // uncomment below to test the property
            //modelInstance.offeringId shouldBe ("TODO")
        }

        // to test the property `quantity` - The quantity the ProductOffering
        should("test quantity") {
            // uncomment below to test the property
            //modelInstance.quantity shouldBe ("TODO")
        }

        // to test the property `isEnabled` - Whether or not the offering can be shown to buyers.
        should("test isEnabled") {
            // uncomment below to test the property
            //modelInstance.isEnabled shouldBe ("TODO")
        }

        // to test the property `isDeleted` - Whether or not the offering has been deleted.
        should("test isDeleted") {
            // uncomment below to test the property
            //modelInstance.isDeleted shouldBe ("TODO")
        }

        // to test the property `price` - Price data for this ProductOffering
        should("test price") {
            // uncomment below to test the property
            //modelInstance.price shouldBe ("TODO")
        }

        // to test the property `readinessStateId` - Processing Profile for this ProductOffering
        should("test readinessStateId") {
            // uncomment below to test the property
            //modelInstance.readinessStateId shouldBe ("TODO")
        }

    }
}
