/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.etsy.models.ListingVideo

class ListingVideoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ListingVideo
        //val modelInstance = ListingVideo()

        // to test the property `videoId` - The unique ID of a video associated with a listing.
        should("test videoId") {
            // uncomment below to test the property
            //modelInstance.videoId shouldBe ("TODO")
        }

        // to test the property `height` - The video height dimension in pixels.
        should("test height") {
            // uncomment below to test the property
            //modelInstance.height shouldBe ("TODO")
        }

        // to test the property `width` - The video width dimension in pixels.
        should("test width") {
            // uncomment below to test the property
            //modelInstance.width shouldBe ("TODO")
        }

        // to test the property `thumbnailUrl` - The url of the video thumbnail.
        should("test thumbnailUrl") {
            // uncomment below to test the property
            //modelInstance.thumbnailUrl shouldBe ("TODO")
        }

        // to test the property `videoUrl` - The url of the video file.
        should("test videoUrl") {
            // uncomment below to test the property
            //modelInstance.videoUrl shouldBe ("TODO")
        }

        // to test the property `videoState` - The current state of a given video. Value is one of `active`, `inactive`, `deleted` or `flagged`.
        should("test videoState") {
            // uncomment below to test the property
            //modelInstance.videoState shouldBe ("TODO")
        }

    }
}
