/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.etsy.models.Money

class MoneyTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Money
        //val modelInstance = Money()

        // to test the property `amount` - The amount of represented by this data.
        should("test amount") {
            // uncomment below to test the property
            //modelInstance.amount shouldBe ("TODO")
        }

        // to test the property `divisor` - The divisor to render the amount.
        should("test divisor") {
            // uncomment below to test the property
            //modelInstance.divisor shouldBe ("TODO")
        }

        // to test the property `currencyCode` - The ISO currency code for this data.
        should("test currencyCode") {
            // uncomment below to test the property
            //modelInstance.currencyCode shouldBe ("TODO")
        }

    }
}
