/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.etsy.models.Pong

class PongTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Pong
        //val modelInstance = Pong()

        // to test the property `applicationId` - The authenticated application's ID
        should("test applicationId") {
            // uncomment below to test the property
            //modelInstance.applicationId shouldBe ("TODO")
        }

    }
}
