/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.etsy.models.Self

class SelfTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Self
        //val modelInstance = Self()

        // to test the property `userId` - The numeric ID of a user. This number is also a valid shop ID for the user's shop.
        should("test userId") {
            // uncomment below to test the property
            //modelInstance.userId shouldBe ("TODO")
        }

        // to test the property `shopId` - The unique positive non-zero numeric ID for an Etsy Shop.
        should("test shopId") {
            // uncomment below to test the property
            //modelInstance.shopId shouldBe ("TODO")
        }

    }
}
