/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.etsy.models.ShippingCarrierMailClass

class ShippingCarrierMailClassTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ShippingCarrierMailClass
        //val modelInstance = ShippingCarrierMailClass()

        // to test the property `mailClassKey` - The unique identifier of this mail class.
        should("test mailClassKey") {
            // uncomment below to test the property
            //modelInstance.mailClassKey shouldBe ("TODO")
        }

        // to test the property `name` - The name of this mail class.
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

    }
}
