/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.etsy.models.ShippingCarrier
import com.etsy.models.ShippingCarrierMailClass

class ShippingCarrierTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ShippingCarrier
        //val modelInstance = ShippingCarrier()

        // to test the property `shippingCarrierId` - The numeric ID of this shipping carrier.
        should("test shippingCarrierId") {
            // uncomment below to test the property
            //modelInstance.shippingCarrierId shouldBe ("TODO")
        }

        // to test the property `name` - The name of this shipping carrier.
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `domesticClasses` - Set of domestic mail classes of this shipping carrier.
        should("test domesticClasses") {
            // uncomment below to test the property
            //modelInstance.domesticClasses shouldBe ("TODO")
        }

        // to test the property `internationalClasses` - Set of international mail classes of this shipping carrier.
        should("test internationalClasses") {
            // uncomment below to test the property
            //modelInstance.internationalClasses shouldBe ("TODO")
        }

    }
}
