/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.etsy.models.ShopListingFile

class ShopListingFileTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ShopListingFile
        //val modelInstance = ShopListingFile()

        // to test the property `listingFileId` - The unique numeric ID of a file associated with a digital listing.
        should("test listingFileId") {
            // uncomment below to test the property
            //modelInstance.listingFileId shouldBe ("TODO")
        }

        // to test the property `listingId` - The numeric ID for the [listing](/documentation/reference#tag/ShopListing) associated to this transaction.
        should("test listingId") {
            // uncomment below to test the property
            //modelInstance.listingId shouldBe ("TODO")
        }

        // to test the property `rank` - The numeric index of the display order position of this file in the listing, starting at 1.
        should("test rank") {
            // uncomment below to test the property
            //modelInstance.rank shouldBe ("TODO")
        }

        // to test the property `filename` - The file name string for a file associated with a digital listing.
        should("test filename") {
            // uncomment below to test the property
            //modelInstance.filename shouldBe ("TODO")
        }

        // to test the property `filesize` - A human-readable format size string for the size of a file.
        should("test filesize") {
            // uncomment below to test the property
            //modelInstance.filesize shouldBe ("TODO")
        }

        // to test the property `sizeBytes` - A number indicating the size of a file, measured in bytes.
        should("test sizeBytes") {
            // uncomment below to test the property
            //modelInstance.sizeBytes shouldBe ("TODO")
        }

        // to test the property `filetype` - A type string indicating a file's MIME type.
        should("test filetype") {
            // uncomment below to test the property
            //modelInstance.filetype shouldBe ("TODO")
        }

        // to test the property `createTimestamp` - The unique numeric ID of a file associated with a digital listing.
        should("test createTimestamp") {
            // uncomment below to test the property
            //modelInstance.createTimestamp shouldBe ("TODO")
        }

        // to test the property `createdTimestamp` - The unique numeric ID of a file associated with a digital listing.
        should("test createdTimestamp") {
            // uncomment below to test the property
            //modelInstance.createdTimestamp shouldBe ("TODO")
        }

    }
}
