/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.etsy.models.ShopProductionPartner

class ShopProductionPartnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ShopProductionPartner
        //val modelInstance = ShopProductionPartner()

        // to test the property `productionPartnerId` - The numeric ID of a production partner.
        should("test productionPartnerId") {
            // uncomment below to test the property
            //modelInstance.productionPartnerId shouldBe ("TODO")
        }

        // to test the property `partnerName` - The name or title of the production partner.
        should("test partnerName") {
            // uncomment below to test the property
            //modelInstance.partnerName shouldBe ("TODO")
        }

        // to test the property `location` - A string representing the production partner location.
        should("test location") {
            // uncomment below to test the property
            //modelInstance.location shouldBe ("TODO")
        }

    }
}
