/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.etsy.models.ShopShippingProfile
import com.etsy.models.ShopShippingProfileDestination
import com.etsy.models.ShopShippingProfileUpgrade

class ShopShippingProfileTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ShopShippingProfile
        //val modelInstance = ShopShippingProfile()

        // to test the property `shippingProfileId` - The numeric ID of the shipping profile.
        should("test shippingProfileId") {
            // uncomment below to test the property
            //modelInstance.shippingProfileId shouldBe ("TODO")
        }

        // to test the property `title` - The name string of this shipping profile.
        should("test title") {
            // uncomment below to test the property
            //modelInstance.title shouldBe ("TODO")
        }

        // to test the property `userId` - The numeric ID for the [user](/documentation/reference#tag/User) who owns the shipping profile.
        should("test userId") {
            // uncomment below to test the property
            //modelInstance.userId shouldBe ("TODO")
        }

        // to test the property `minProcessingDays` - The minimum number of days for processing the listing.
        should("test minProcessingDays") {
            // uncomment below to test the property
            //modelInstance.minProcessingDays shouldBe ("TODO")
        }

        // to test the property `maxProcessingDays` - The maximum number of days for processing the listing.
        should("test maxProcessingDays") {
            // uncomment below to test the property
            //modelInstance.maxProcessingDays shouldBe ("TODO")
        }

        // to test the property `processingDaysDisplayLabel` - Translated display label string for processing days.
        should("test processingDaysDisplayLabel") {
            // uncomment below to test the property
            //modelInstance.processingDaysDisplayLabel shouldBe ("TODO")
        }

        // to test the property `originCountryIso` - The ISO code of the country from which the listing ships.
        should("test originCountryIso") {
            // uncomment below to test the property
            //modelInstance.originCountryIso shouldBe ("TODO")
        }

        // to test the property `isDeleted` - When true, someone deleted this shipping profile.
        should("test isDeleted") {
            // uncomment below to test the property
            //modelInstance.isDeleted shouldBe ("TODO")
        }

        // to test the property `shippingProfileDestinations` - A list of [shipping profile destinations](/documentation/reference/#operation/createShopShippingProfileDestination) available for this shipping profile.
        should("test shippingProfileDestinations") {
            // uncomment below to test the property
            //modelInstance.shippingProfileDestinations shouldBe ("TODO")
        }

        // to test the property `shippingProfileUpgrades` - A list of [shipping profile upgrades](/documentation/reference/#operation/createShopShippingProfileUpgrade) available for this shipping profile.
        should("test shippingProfileUpgrades") {
            // uncomment below to test the property
            //modelInstance.shippingProfileUpgrades shouldBe ("TODO")
        }

        // to test the property `originPostalCode` - The postal code string (not necessarily a number) for the location from which the listing ships. Required if the `origin_country_iso` supports postal codes. See the [Fulfillment Tutorial docs](https://developer.etsy.com/documentation/tutorials/fulfillment/#countries-requiring-postal-codes) for more info
        should("test originPostalCode") {
            // uncomment below to test the property
            //modelInstance.originPostalCode shouldBe ("TODO")
        }

        // to test the property `profileType`
        should("test profileType") {
            // uncomment below to test the property
            //modelInstance.profileType shouldBe ("TODO")
        }

        // to test the property `domesticHandlingFee` - The domestic handling fee added to buyer's shipping total - only available for calculated shipping profiles.
        should("test domesticHandlingFee") {
            // uncomment below to test the property
            //modelInstance.domesticHandlingFee shouldBe ("TODO")
        }

        // to test the property `internationalHandlingFee` - The international handling fee added to buyer's shipping total - only available for calculated shipping profiles.
        should("test internationalHandlingFee") {
            // uncomment below to test the property
            //modelInstance.internationalHandlingFee shouldBe ("TODO")
        }

    }
}
