/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.etsy.models.ShopReceipts
import com.etsy.models.ShopReceipt

class ShopReceiptsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ShopReceipts
        //val modelInstance = ShopReceipts()

        // to test the property `count` - The number of Shop Receipts found.
        should("test count") {
            // uncomment below to test the property
            //modelInstance.count shouldBe ("TODO")
        }

        // to test the property `results` - List of Shop Receipt resources found, with all Shop Receipt fields for each resource.
        should("test results") {
            // uncomment below to test the property
            //modelInstance.results shouldBe ("TODO")
        }

    }
}
