/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.etsy.models.ShopReceiptShipment

class ShopReceiptShipmentTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ShopReceiptShipment
        //val modelInstance = ShopReceiptShipment()

        // to test the property `receiptShippingId` - The unique numeric ID of a Shop Receipt Shipment record.
        should("test receiptShippingId") {
            // uncomment below to test the property
            //modelInstance.receiptShippingId shouldBe ("TODO")
        }

        // to test the property `shipmentNotificationTimestamp` - The time at which Etsy notified the buyer of the shipment event, in epoch seconds.
        should("test shipmentNotificationTimestamp") {
            // uncomment below to test the property
            //modelInstance.shipmentNotificationTimestamp shouldBe ("TODO")
        }

        // to test the property `carrierName` - The name string for the carrier/company responsible for delivering the shipment.
        should("test carrierName") {
            // uncomment below to test the property
            //modelInstance.carrierName shouldBe ("TODO")
        }

        // to test the property `trackingCode` - The tracking code string provided by the carrier/company for the shipment.
        should("test trackingCode") {
            // uncomment below to test the property
            //modelInstance.trackingCode shouldBe ("TODO")
        }

    }
}
