/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.etsy.models.ShopSection

class ShopSectionTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ShopSection
        //val modelInstance = ShopSection()

        // to test the property `shopSectionId` - The numeric ID of a section in a specific Etsy shop.
        should("test shopSectionId") {
            // uncomment below to test the property
            //modelInstance.shopSectionId shouldBe ("TODO")
        }

        // to test the property `title` - The title string for a shop section.
        should("test title") {
            // uncomment below to test the property
            //modelInstance.title shouldBe ("TODO")
        }

        // to test the property `rank` - The positive non-zero numeric position of this section in the section display order for a shop, with rank 1 sections appearing first.
        should("test rank") {
            // uncomment below to test the property
            //modelInstance.rank shouldBe ("TODO")
        }

        // to test the property `userId` - The numeric ID of the [user](/documentation/reference#tag/User) who owns this shop section.
        should("test userId") {
            // uncomment below to test the property
            //modelInstance.userId shouldBe ("TODO")
        }

        // to test the property `activeListingCount` - The number of active listings in one section of a specific Etsy shop.
        should("test activeListingCount") {
            // uncomment below to test the property
            //modelInstance.activeListingCount shouldBe ("TODO")
        }

    }
}
