/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.etsy.models.ShopReceiptTransactions
import com.etsy.models.ShopReceiptTransaction

class ShopReceiptTransactionsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ShopReceiptTransactions
        //val modelInstance = ShopReceiptTransactions()

        // to test the property `count` - The number of ShopReceiptTransaction resources found.
        should("test count") {
            // uncomment below to test the property
            //modelInstance.count shouldBe ("TODO")
        }

        // to test the property `results` - The ShopReceiptTransaction resources found.
        should("test results") {
            // uncomment below to test the property
            //modelInstance.results shouldBe ("TODO")
        }

    }
}
