/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.etsy.models.TaxonomyPropertyScale

class TaxonomyPropertyScaleTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TaxonomyPropertyScale
        //val modelInstance = TaxonomyPropertyScale()

        // to test the property `scaleId` - The unique numeric ID of a scale.
        should("test scaleId") {
            // uncomment below to test the property
            //modelInstance.scaleId shouldBe ("TODO")
        }

        // to test the property `displayName` - The name string for a scale.
        should("test displayName") {
            // uncomment below to test the property
            //modelInstance.displayName shouldBe ("TODO")
        }

        // to test the property `description` - The description string for a scale.
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

    }
}
