/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.etsy.models.TransactionVariations

class TransactionVariationsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TransactionVariations
        //val modelInstance = TransactionVariations()

        // to test the property `propertyId` - The variation property ID.
        should("test propertyId") {
            // uncomment below to test the property
            //modelInstance.propertyId shouldBe ("TODO")
        }

        // to test the property `valueId` - The ID of the variation value selected.
        should("test valueId") {
            // uncomment below to test the property
            //modelInstance.valueId shouldBe ("TODO")
        }

        // to test the property `formattedName` - Formatted name of the variation.
        should("test formattedName") {
            // uncomment below to test the property
            //modelInstance.formattedName shouldBe ("TODO")
        }

        // to test the property `formattedValue` - Value of the variation entered by the buyer.
        should("test formattedValue") {
            // uncomment below to test the property
            //modelInstance.formattedValue shouldBe ("TODO")
        }

    }
}
