/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.etsy.models.TypeDiscriminator

class TypeDiscriminatorTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TypeDiscriminator
        //val modelInstance = TypeDiscriminator()

        // to test the property `type` - field used to determine the type of the object when deserializing union type responses
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

    }
}
