/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.etsy.models.UpdateVariationImagesRequestVariationImagesInner

class UpdateVariationImagesRequestVariationImagesInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UpdateVariationImagesRequestVariationImagesInner
        //val modelInstance = UpdateVariationImagesRequestVariationImagesInner()

        // to test the property `propertyId`
        should("test propertyId") {
            // uncomment below to test the property
            //modelInstance.propertyId shouldBe ("TODO")
        }

        // to test the property `valueId`
        should("test valueId") {
            // uncomment below to test the property
            //modelInstance.valueId shouldBe ("TODO")
        }

        // to test the property `imageId`
        should("test imageId") {
            // uncomment below to test the property
            //modelInstance.imageId shouldBe ("TODO")
        }

    }
}
