/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.etsy.models.UpdateListingInventoryRequestProductsInnerOfferingsInner

class UpdateListingInventoryRequestProductsInnerOfferingsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UpdateListingInventoryRequestProductsInnerOfferingsInner
        //val modelInstance = UpdateListingInventoryRequestProductsInnerOfferingsInner()

        // to test the property `price` - The price of the product.
        should("test price") {
            // uncomment below to test the property
            //modelInstance.price shouldBe ("TODO")
        }

        // to test the property `quantity` - How many of this product are available?
        should("test quantity") {
            // uncomment below to test the property
            //modelInstance.quantity shouldBe ("TODO")
        }

        // to test the property `isEnabled` - True if the offering is shown to buyers
        should("test isEnabled") {
            // uncomment below to test the property
            //modelInstance.isEnabled shouldBe ("TODO")
        }

        // to test the property `readinessStateId` - The numeric ID of the [processing profile](/documentation/reference#operation/getShopReadinessStateDefinition) associated with the listing. Required when listing type is `physical`.
        should("test readinessStateId") {
            // uncomment below to test the property
            //modelInstance.readinessStateId shouldBe ("TODO")
        }

    }
}
