/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.etsy.apis.LedgerEntryApi
import com.etsy.models.ErrorSchema
import com.etsy.models.PaymentAccountLedgerEntries
import com.etsy.models.PaymentAccountLedgerEntry

class LedgerEntryApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of LedgerEntryApi
        //val apiInstance = LedgerEntryApi()

        // to test getShopPaymentAccountLedgerEntries
        should("test getShopPaymentAccountLedgerEntries") {
            // uncomment below to test getShopPaymentAccountLedgerEntries
            //val shopId : kotlin.Long = 789 // kotlin.Long | The unique positive non-zero numeric ID for an Etsy Shop.
            //val minCreated : kotlin.Int = 56 // kotlin.Int | The earliest unix timestamp for when a record was created.
            //val maxCreated : kotlin.Int = 56 // kotlin.Int | The latest unix timestamp for when a record was created.
            //val limit : kotlin.Int = 56 // kotlin.Int | The maximum number of results to return.
            //val offset : kotlin.Int = 56 // kotlin.Int | The number of records to skip before selecting the first result.
            //val result : PaymentAccountLedgerEntries = apiInstance.getShopPaymentAccountLedgerEntries(shopId, minCreated, maxCreated, limit, offset)
            //result shouldBe ("TODO")
        }

        // to test getShopPaymentAccountLedgerEntry
        should("test getShopPaymentAccountLedgerEntry") {
            // uncomment below to test getShopPaymentAccountLedgerEntry
            //val shopId : kotlin.Long = 789 // kotlin.Long | The unique positive non-zero numeric ID for an Etsy Shop.
            //val ledgerEntryId : kotlin.Long = 789 // kotlin.Long | The unique ID of the shop owner ledger entry.
            //val result : PaymentAccountLedgerEntry = apiInstance.getShopPaymentAccountLedgerEntry(shopId, ledgerEntryId)
            //result shouldBe ("TODO")
        }

    }
}
