/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.etsy.apis.OtherApi
import com.etsy.models.ErrorSchema
import com.etsy.models.Pong

class OtherApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OtherApi
        //val apiInstance = OtherApi()

        // to test ping
        should("test ping") {
            // uncomment below to test ping
            //val result : Pong = apiInstance.ping()
            //result shouldBe ("TODO")
        }

        // to test tokenScopes
        should("test tokenScopes") {
            // uncomment below to test tokenScopes
            //val token : kotlin.String = token_example // kotlin.String | 
            //val result : kotlin.String = apiInstance.tokenScopes(token)
            //result shouldBe ("TODO")
        }

    }
}
