/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.etsy.apis.PaymentApi
import com.etsy.models.ErrorSchema
import com.etsy.models.Payments

class PaymentApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PaymentApi
        //val apiInstance = PaymentApi()

        // to test getPaymentAccountLedgerEntryPayments
        should("test getPaymentAccountLedgerEntryPayments") {
            // uncomment below to test getPaymentAccountLedgerEntryPayments
            //val shopId : kotlin.Long = 789 // kotlin.Long | The unique positive non-zero numeric ID for an Etsy Shop.
            //val ledgerEntryIds : kotlin.collections.List<kotlin.Long> =  // kotlin.collections.List<kotlin.Long> | 
            //val result : Payments = apiInstance.getPaymentAccountLedgerEntryPayments(shopId, ledgerEntryIds)
            //result shouldBe ("TODO")
        }

        // to test getPayments
        should("test getPayments") {
            // uncomment below to test getPayments
            //val shopId : kotlin.Long = 789 // kotlin.Long | The unique positive non-zero numeric ID for an Etsy Shop.
            //val paymentIds : kotlin.collections.List<kotlin.Long> =  // kotlin.collections.List<kotlin.Long> | A comma-separated array of Payment IDs numbers.
            //val result : Payments = apiInstance.getPayments(shopId, paymentIds)
            //result shouldBe ("TODO")
        }

        // to test getShopPaymentByReceiptId
        should("test getShopPaymentByReceiptId") {
            // uncomment below to test getShopPaymentByReceiptId
            //val shopId : kotlin.Long = 789 // kotlin.Long | The unique positive non-zero numeric ID for an Etsy Shop.
            //val receiptId : kotlin.Long = 789 // kotlin.Long | The numeric ID for the [receipt](/documentation/reference#tag/Shop-Receipt) associated to this transaction.
            //val result : Payments = apiInstance.getShopPaymentByReceiptId(shopId, receiptId)
            //result shouldBe ("TODO")
        }

    }
}
