/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.etsy.apis.ReviewApi
import com.etsy.models.ErrorSchema
import com.etsy.models.ListingReviews
import com.etsy.models.TransactionReviews

class ReviewApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ReviewApi
        //val apiInstance = ReviewApi()

        // to test getReviewsByListing
        should("test getReviewsByListing") {
            // uncomment below to test getReviewsByListing
            //val listingId : kotlin.Long = 789 // kotlin.Long | The numeric ID for the [listing](/documentation/reference#tag/ShopListing) associated to this transaction.
            //val limit : kotlin.Int = 56 // kotlin.Int | The maximum number of results to return.
            //val offset : kotlin.Int = 56 // kotlin.Int | The number of records to skip before selecting the first result.
            //val minCreated : kotlin.Int = 56 // kotlin.Int | The earliest unix timestamp for when a record was created.
            //val maxCreated : kotlin.Int = 56 // kotlin.Int | The latest unix timestamp for when a record was created.
            //val result : ListingReviews = apiInstance.getReviewsByListing(listingId, limit, offset, minCreated, maxCreated)
            //result shouldBe ("TODO")
        }

        // to test getReviewsByShop
        should("test getReviewsByShop") {
            // uncomment below to test getReviewsByShop
            //val shopId : kotlin.Long = 789 // kotlin.Long | The unique positive non-zero numeric ID for an Etsy Shop.
            //val limit : kotlin.Int = 56 // kotlin.Int | The maximum number of results to return.
            //val offset : kotlin.Int = 56 // kotlin.Int | The number of records to skip before selecting the first result.
            //val minCreated : kotlin.Int = 56 // kotlin.Int | The earliest unix timestamp for when a record was created.
            //val maxCreated : kotlin.Int = 56 // kotlin.Int | The latest unix timestamp for when a record was created.
            //val result : TransactionReviews = apiInstance.getReviewsByShop(shopId, limit, offset, minCreated, maxCreated)
            //result shouldBe ("TODO")
        }

    }
}
