/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.etsy.apis.ShopListingInventoryApi
import com.etsy.models.ErrorSchema
import com.etsy.models.ListingInventory
import com.etsy.models.ListingInventoryWithAssociations
import com.etsy.models.UpdateListingInventoryRequest

class ShopListingInventoryApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ShopListingInventoryApi
        //val apiInstance = ShopListingInventoryApi()

        // to test getListingInventory
        should("test getListingInventory") {
            // uncomment below to test getListingInventory
            //val listingId : kotlin.Long = 789 // kotlin.Long | The numeric ID for the [listing](/documentation/reference#tag/ShopListing) associated to this transaction.
            //val showDeleted : kotlin.Boolean = true // kotlin.Boolean | A boolean value for inventory whether to include deleted products and their offerings. Default value is false.
            //val includes : kotlin.String = includes_example // kotlin.String | An enumerated string that attaches a valid association. Default value is null.
            //val legacy : kotlin.Boolean = true // kotlin.Boolean | This parameter needed to enable new parameters and response values related to processing profiles.
            //val result : ListingInventoryWithAssociations = apiInstance.getListingInventory(listingId, showDeleted, includes, legacy)
            //result shouldBe ("TODO")
        }

        // to test updateListingInventory
        should("test updateListingInventory") {
            // uncomment below to test updateListingInventory
            //val listingId : kotlin.Long = 789 // kotlin.Long | The numeric ID for the [listing](/documentation/reference#tag/ShopListing) associated to this transaction.
            //val legacy : kotlin.Boolean = true // kotlin.Boolean | This parameter needed to enable new parameters and response values related to processing profiles.
            //val updateListingInventoryRequest : UpdateListingInventoryRequest =  // UpdateListingInventoryRequest | 
            //val result : ListingInventory = apiInstance.updateListingInventory(listingId, legacy, updateListingInventoryRequest)
            //result shouldBe ("TODO")
        }

    }
}
