/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.etsy.apis.ShopListingOfferingApi
import com.etsy.models.ErrorSchema
import com.etsy.models.ListingInventoryProductOffering

class ShopListingOfferingApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ShopListingOfferingApi
        //val apiInstance = ShopListingOfferingApi()

        // to test getListingOffering
        should("test getListingOffering") {
            // uncomment below to test getListingOffering
            //val listingId : kotlin.Long = 789 // kotlin.Long | 
            //val productId : kotlin.Long = 789 // kotlin.Long | 
            //val productOfferingId : kotlin.Long = 789 // kotlin.Long | 
            //val legacy : kotlin.Boolean = true // kotlin.Boolean | This parameter needed to enable new parameters and response values related to processing profiles.
            //val result : ListingInventoryProductOffering = apiInstance.getListingOffering(listingId, productId, productOfferingId, legacy)
            //result shouldBe ("TODO")
        }

    }
}
