/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.etsy.apis.ShopReturnPolicyApi
import com.etsy.models.ErrorSchema
import com.etsy.models.ShopReturnPolicies
import com.etsy.models.ShopReturnPolicy

class ShopReturnPolicyApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ShopReturnPolicyApi
        //val apiInstance = ShopReturnPolicyApi()

        // to test consolidateShopReturnPolicies
        should("test consolidateShopReturnPolicies") {
            // uncomment below to test consolidateShopReturnPolicies
            //val shopId : kotlin.Long = 789 // kotlin.Long | The unique positive non-zero numeric ID for an Etsy Shop.
            //val sourceReturnPolicyId : kotlin.Long = 789 // kotlin.Long | The numeric ID of the [Return Policy](/documentation/reference#operation/getShopReturnPolicies).
            //val destinationReturnPolicyId : kotlin.Long = 789 // kotlin.Long | The numeric ID of the [Return Policy](/documentation/reference#operation/getShopReturnPolicies).
            //val result : ShopReturnPolicy = apiInstance.consolidateShopReturnPolicies(shopId, sourceReturnPolicyId, destinationReturnPolicyId)
            //result shouldBe ("TODO")
        }

        // to test createShopReturnPolicy
        should("test createShopReturnPolicy") {
            // uncomment below to test createShopReturnPolicy
            //val shopId : kotlin.Long = 789 // kotlin.Long | The unique positive non-zero numeric ID for an Etsy Shop.
            //val acceptsReturns : kotlin.Boolean = true // kotlin.Boolean | 
            //val acceptsExchanges : kotlin.Boolean = true // kotlin.Boolean | 
            //val returnDeadline : kotlin.Int = 56 // kotlin.Int | The deadline for the Return Policy, measured in days. The value must be one of the following: [7, 14, 21, 30, 45, 60, 90].
            //val result : ShopReturnPolicy = apiInstance.createShopReturnPolicy(shopId, acceptsReturns, acceptsExchanges, returnDeadline)
            //result shouldBe ("TODO")
        }

        // to test deleteShopReturnPolicy
        should("test deleteShopReturnPolicy") {
            // uncomment below to test deleteShopReturnPolicy
            //val shopId : kotlin.Long = 789 // kotlin.Long | The unique positive non-zero numeric ID for an Etsy Shop.
            //val returnPolicyId : kotlin.Long = 789 // kotlin.Long | The numeric ID of the [Return Policy](/documentation/reference#operation/getShopReturnPolicies).
            //apiInstance.deleteShopReturnPolicy(shopId, returnPolicyId)
        }

        // to test getShopReturnPolicies
        should("test getShopReturnPolicies") {
            // uncomment below to test getShopReturnPolicies
            //val shopId : kotlin.Long = 789 // kotlin.Long | The unique positive non-zero numeric ID for an Etsy Shop.
            //val result : ShopReturnPolicies = apiInstance.getShopReturnPolicies(shopId)
            //result shouldBe ("TODO")
        }

        // to test getShopReturnPolicy
        should("test getShopReturnPolicy") {
            // uncomment below to test getShopReturnPolicy
            //val shopId : kotlin.Long = 789 // kotlin.Long | The unique positive non-zero numeric ID for an Etsy Shop.
            //val returnPolicyId : kotlin.Long = 789 // kotlin.Long | The numeric ID of the [Return Policy](/documentation/reference#operation/getShopReturnPolicies).
            //val result : ShopReturnPolicy = apiInstance.getShopReturnPolicy(shopId, returnPolicyId)
            //result shouldBe ("TODO")
        }

        // to test updateShopReturnPolicy
        should("test updateShopReturnPolicy") {
            // uncomment below to test updateShopReturnPolicy
            //val shopId : kotlin.Long = 789 // kotlin.Long | The unique positive non-zero numeric ID for an Etsy Shop.
            //val returnPolicyId : kotlin.Long = 789 // kotlin.Long | The numeric ID of the [Return Policy](/documentation/reference#operation/getShopReturnPolicies).
            //val acceptsReturns : kotlin.Boolean = true // kotlin.Boolean | 
            //val acceptsExchanges : kotlin.Boolean = true // kotlin.Boolean | 
            //val returnDeadline : kotlin.Int = 56 // kotlin.Int | The deadline for the Return Policy, measured in days. The value must be one of the following: [7, 14, 21, 30, 45, 60, 90].
            //val result : ShopReturnPolicy = apiInstance.updateShopReturnPolicy(shopId, returnPolicyId, acceptsReturns, acceptsExchanges, returnDeadline)
            //result shouldBe ("TODO")
        }

    }
}
