/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.etsy.apis.ShopListingTranslationApi
import com.etsy.models.ErrorSchema
import com.etsy.models.ListingTranslation

class ShopListingTranslationApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ShopListingTranslationApi
        //val apiInstance = ShopListingTranslationApi()

        // to test createListingTranslation
        should("test createListingTranslation") {
            // uncomment below to test createListingTranslation
            //val shopId : kotlin.Long = 789 // kotlin.Long | The unique positive non-zero numeric ID for an Etsy Shop.
            //val listingId : kotlin.Long = 789 // kotlin.Long | The numeric ID for the [listing](/documentation/reference#tag/ShopListing) associated to this transaction.
            //val language : kotlin.String = language_example // kotlin.String | The IETF language tag for the language of this translation. Ex: `de`, `en`, `es`, `fr`, `it`, `ja`, `nl`, `pl`, `pt`.
            //val title : kotlin.String = title_example // kotlin.String | The title of the Listing of this Translation.
            //val description : kotlin.String = description_example // kotlin.String | The description of the Listing of this Translation.
            //val tags : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | The tags of the Listing of this Translation.
            //val result : ListingTranslation = apiInstance.createListingTranslation(shopId, listingId, language, title, description, tags)
            //result shouldBe ("TODO")
        }

        // to test getListingTranslation
        should("test getListingTranslation") {
            // uncomment below to test getListingTranslation
            //val shopId : kotlin.Long = 789 // kotlin.Long | The unique positive non-zero numeric ID for an Etsy Shop.
            //val listingId : kotlin.Long = 789 // kotlin.Long | The numeric ID for the [listing](/documentation/reference#tag/ShopListing) associated to this transaction.
            //val language : kotlin.String = language_example // kotlin.String | The IETF language tag for the language of this translation. Ex: `de`, `en`, `es`, `fr`, `it`, `ja`, `nl`, `pl`, `pt`.
            //val result : ListingTranslation = apiInstance.getListingTranslation(shopId, listingId, language)
            //result shouldBe ("TODO")
        }

        // to test updateListingTranslation
        should("test updateListingTranslation") {
            // uncomment below to test updateListingTranslation
            //val shopId : kotlin.Long = 789 // kotlin.Long | The unique positive non-zero numeric ID for an Etsy Shop.
            //val listingId : kotlin.Long = 789 // kotlin.Long | The numeric ID for the [listing](/documentation/reference#tag/ShopListing) associated to this transaction.
            //val language : kotlin.String = language_example // kotlin.String | The IETF language tag for the language of this translation. Ex: `de`, `en`, `es`, `fr`, `it`, `ja`, `nl`, `pl`, `pt`.
            //val title : kotlin.String = title_example // kotlin.String | The title of the Listing of this Translation.
            //val description : kotlin.String = description_example // kotlin.String | The description of the Listing of this Translation.
            //val tags : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | The tags of the Listing of this Translation.
            //val result : ListingTranslation = apiInstance.updateListingTranslation(shopId, listingId, language, title, description, tags)
            //result shouldBe ("TODO")
        }

    }
}
