/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.etsy.apis.ShopSectionApi
import com.etsy.models.ErrorSchema
import com.etsy.models.ShopSection
import com.etsy.models.ShopSections

class ShopSectionApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ShopSectionApi
        //val apiInstance = ShopSectionApi()

        // to test createShopSection
        should("test createShopSection") {
            // uncomment below to test createShopSection
            //val shopId : kotlin.Long = 789 // kotlin.Long | The unique positive non-zero numeric ID for an Etsy Shop.
            //val title : kotlin.String = title_example // kotlin.String | The title string for a shop section.
            //val result : ShopSection = apiInstance.createShopSection(shopId, title)
            //result shouldBe ("TODO")
        }

        // to test deleteShopSection
        should("test deleteShopSection") {
            // uncomment below to test deleteShopSection
            //val shopId : kotlin.Long = 789 // kotlin.Long | The unique positive non-zero numeric ID for an Etsy Shop.
            //val shopSectionId : kotlin.Long = 789 // kotlin.Long | The numeric ID of a section in a specific Etsy shop.
            //apiInstance.deleteShopSection(shopId, shopSectionId)
        }

        // to test getShopSection
        should("test getShopSection") {
            // uncomment below to test getShopSection
            //val shopId : kotlin.Long = 789 // kotlin.Long | The unique positive non-zero numeric ID for an Etsy Shop.
            //val shopSectionId : kotlin.Long = 789 // kotlin.Long | The numeric ID of a section in a specific Etsy shop.
            //val result : ShopSection = apiInstance.getShopSection(shopId, shopSectionId)
            //result shouldBe ("TODO")
        }

        // to test getShopSections
        should("test getShopSections") {
            // uncomment below to test getShopSections
            //val shopId : kotlin.Long = 789 // kotlin.Long | The unique positive non-zero numeric ID for an Etsy Shop.
            //val result : ShopSections = apiInstance.getShopSections(shopId)
            //result shouldBe ("TODO")
        }

        // to test updateShopSection
        should("test updateShopSection") {
            // uncomment below to test updateShopSection
            //val shopId : kotlin.Long = 789 // kotlin.Long | The unique positive non-zero numeric ID for an Etsy Shop.
            //val shopSectionId : kotlin.Long = 789 // kotlin.Long | The numeric ID of a section in a specific Etsy shop.
            //val title : kotlin.String = title_example // kotlin.String | The title string for a shop section.
            //val result : ShopSection = apiInstance.updateShopSection(shopId, shopSectionId, title)
            //result shouldBe ("TODO")
        }

    }
}
