/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.etsy.apis.ShopProductionPartnerApi
import com.etsy.models.ErrorSchema
import com.etsy.models.ShopProductionPartners

class ShopProductionPartnerApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ShopProductionPartnerApi
        //val apiInstance = ShopProductionPartnerApi()

        // to test getShopProductionPartners
        should("test getShopProductionPartners") {
            // uncomment below to test getShopProductionPartners
            //val shopId : kotlin.Long = 789 // kotlin.Long | The unique positive non-zero numeric ID for an Etsy Shop.
            //val result : ShopProductionPartners = apiInstance.getShopProductionPartners(shopId)
            //result shouldBe ("TODO")
        }

    }
}
