/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.etsy.apis.ShopHolidayPreferencesApi
import com.etsy.models.ErrorSchema
import com.etsy.models.ShopHolidayPreference

class ShopHolidayPreferencesApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ShopHolidayPreferencesApi
        //val apiInstance = ShopHolidayPreferencesApi()

        // to test getHolidayPreferences
        should("test getHolidayPreferences") {
            // uncomment below to test getHolidayPreferences
            //val shopId : kotlin.Long = 789 // kotlin.Long | The unique positive non-zero numeric ID for an Etsy Shop.
            //val result : kotlin.collections.List<ShopHolidayPreference> = apiInstance.getHolidayPreferences(shopId)
            //result shouldBe ("TODO")
        }

        // to test updateHolidayPreferences
        should("test updateHolidayPreferences") {
            // uncomment below to test updateHolidayPreferences
            //val shopId : kotlin.Long = 789 // kotlin.Long | The unique positive non-zero numeric ID for an Etsy Shop.
            //val holidayId : kotlin.String = holidayId_example // kotlin.String | The unique id that maps to the holiday a country observes. See the [Fulfillment Tutorial docs](https://developer.etsy.com/documentation/tutorials/fulfillment/#country-holidays) for more info
            //val isWorking : kotlin.Boolean = true // kotlin.Boolean | A boolean value for whether the shop will process orders on a particular holiday.
            //val result : ShopHolidayPreference = apiInstance.updateHolidayPreferences(shopId, holidayId, isWorking)
            //result shouldBe ("TODO")
        }

    }
}
