/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.etsy.apis.ShopListingProductApi
import com.etsy.models.ErrorSchema
import com.etsy.models.ListingInventoryProduct

class ShopListingProductApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ShopListingProductApi
        //val apiInstance = ShopListingProductApi()

        // to test getListingProduct
        should("test getListingProduct") {
            // uncomment below to test getListingProduct
            //val listingId : kotlin.Long = 789 // kotlin.Long | The listing to return a ListingProduct for.
            //val productId : kotlin.Long = 789 // kotlin.Long | The numeric ID for a specific [product](/documentation/reference#tag/ShopListing-Product) purchased from a listing.
            //val legacy : kotlin.Boolean = true // kotlin.Boolean | This parameter needed to enable new parameters and response values related to processing profiles.
            //val result : ListingInventoryProduct = apiInstance.getListingProduct(listingId, productId, legacy)
            //result shouldBe ("TODO")
        }

    }
}
