/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.etsy.apis.ShopShippingProfileApi
import com.etsy.models.ErrorSchema
import com.etsy.models.ShippingCarriers
import com.etsy.models.ShopShippingProfile
import com.etsy.models.ShopShippingProfileDestination
import com.etsy.models.ShopShippingProfileDestinations
import com.etsy.models.ShopShippingProfileUpgrade
import com.etsy.models.ShopShippingProfileUpgrades
import com.etsy.models.ShopShippingProfiles

class ShopShippingProfileApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ShopShippingProfileApi
        //val apiInstance = ShopShippingProfileApi()

        // to test createShopShippingProfile
        should("test createShopShippingProfile") {
            // uncomment below to test createShopShippingProfile
            //val shopId : kotlin.Long = 789 // kotlin.Long | The unique positive non-zero numeric ID for an Etsy Shop.
            //val title : kotlin.String = title_example // kotlin.String | The name string of this shipping profile.
            //val originCountryIso : kotlin.String = originCountryIso_example // kotlin.String | The ISO code of the country from which the listing ships.
            //val primaryCost : kotlin.Float = 3.4 // kotlin.Float | The cost of shipping to this country/region alone, measured in the store's default currency.
            //val secondaryCost : kotlin.Float = 3.4 // kotlin.Float | The cost of shipping to this country/region with another item, measured in the store's default currency.
            //val minProcessingTime : kotlin.Int = 56 // kotlin.Int | The minimum time required to process to ship listings with this shipping profile.
            //val maxProcessingTime : kotlin.Int = 56 // kotlin.Int | The maximum processing time the listing needs to ship.
            //val processingTimeUnit : kotlin.String = processingTimeUnit_example // kotlin.String | The unit used to represent how long a processing time is. A week is equivalent to the set processing schedule (default to 5 business days). If none is provided, the unit is set to \\\"business_days\\\".
            //val destinationCountryIso : kotlin.String = destinationCountryIso_example // kotlin.String | The ISO code of the country to which the listing ships. If null, request sets destination to destination_region. Required if destination_region is null or not provided.
            //val destinationRegion : kotlin.String = destinationRegion_example // kotlin.String | The code of the region to which the listing ships. A region represents a set of countries. Supported regions are Europe Union and Non-Europe Union (countries in Europe not in EU). If `none`, request sets destination to destination_country_iso. Required if destination_country_iso is null or not provided.
            //val originPostalCode : kotlin.String = originPostalCode_example // kotlin.String | The postal code string (not necessarily a number) for the location from which the listing ships. Required if the `origin_country_iso` supports postal codes. See the [Fulfillment Tutorial docs](https://developer.etsy.com/documentation/tutorials/fulfillment/#countries-requiring-postal-codes) for more info
            //val shippingCarrierId : kotlin.Int = 56 // kotlin.Int | The unique ID of a supported shipping carrier, which is used to calculate an Estimated Delivery Date. **Required with `mail_class`** if `min_delivery_days` and `max_delivery_days` are null.
            //val mailClass : kotlin.String = mailClass_example // kotlin.String | The unique ID string of a shipping carrier's mail class, which is used to calculate an estimated delivery date. **Required with `shipping_carrier_id`** if `min_delivery_days` and `max_delivery_days` are null.
            //val minDeliveryDays : kotlin.Int = 56 // kotlin.Int | The minimum number of business days a buyer can expect to wait to receive their purchased item once it has shipped. **Required with `max_delivery_days`** if `mail_class` is null.
            //val maxDeliveryDays : kotlin.Int = 56 // kotlin.Int | The maximum number of business days a buyer can expect to wait to receive their purchased item once it has shipped. **Required with `min_delivery_days`** if `mail_class` is null.
            //val result : ShopShippingProfile = apiInstance.createShopShippingProfile(shopId, title, originCountryIso, primaryCost, secondaryCost, minProcessingTime, maxProcessingTime, processingTimeUnit, destinationCountryIso, destinationRegion, originPostalCode, shippingCarrierId, mailClass, minDeliveryDays, maxDeliveryDays)
            //result shouldBe ("TODO")
        }

        // to test createShopShippingProfileDestination
        should("test createShopShippingProfileDestination") {
            // uncomment below to test createShopShippingProfileDestination
            //val shopId : kotlin.Long = 789 // kotlin.Long | The unique positive non-zero numeric ID for an Etsy Shop.
            //val shippingProfileId : kotlin.Long = 789 // kotlin.Long | The numeric ID of the [shipping profile](/documentation/reference#operation/getShopShippingProfile) associated with the listing. Required when listing type is `physical`.
            //val primaryCost : kotlin.Float = 3.4 // kotlin.Float | The cost of shipping to this country/region alone, measured in the store's default currency.
            //val secondaryCost : kotlin.Float = 3.4 // kotlin.Float | The cost of shipping to this country/region with another item, measured in the store's default currency.
            //val destinationCountryIso : kotlin.String = destinationCountryIso_example // kotlin.String | The ISO code of the country to which the listing ships. If null, request sets destination to destination_region. Required if destination_region is null or not provided.
            //val destinationRegion : kotlin.String = destinationRegion_example // kotlin.String | The code of the region to which the listing ships. A region represents a set of countries. Supported regions are Europe Union and Non-Europe Union (countries in Europe not in EU). If `none`, request sets destination to destination_country_iso. Required if destination_country_iso is null or not provided.
            //val shippingCarrierId : kotlin.Int = 56 // kotlin.Int | The unique ID of a supported shipping carrier, which is used to calculate an Estimated Delivery Date. **Required with `mail_class`** if `min_delivery_days` and `max_delivery_days` are null.
            //val mailClass : kotlin.String = mailClass_example // kotlin.String | The unique ID string of a shipping carrier's mail class, which is used to calculate an estimated delivery date. **Required with `shipping_carrier_id`** if `min_delivery_days` and `max_delivery_days` are null.
            //val minDeliveryDays : kotlin.Int = 56 // kotlin.Int | The minimum number of business days a buyer can expect to wait to receive their purchased item once it has shipped. **Required with `max_delivery_days`** if `mail_class` is null.
            //val maxDeliveryDays : kotlin.Int = 56 // kotlin.Int | The maximum number of business days a buyer can expect to wait to receive their purchased item once it has shipped. **Required with `min_delivery_days`** if `mail_class` is null.
            //val result : ShopShippingProfileDestination = apiInstance.createShopShippingProfileDestination(shopId, shippingProfileId, primaryCost, secondaryCost, destinationCountryIso, destinationRegion, shippingCarrierId, mailClass, minDeliveryDays, maxDeliveryDays)
            //result shouldBe ("TODO")
        }

        // to test createShopShippingProfileUpgrade
        should("test createShopShippingProfileUpgrade") {
            // uncomment below to test createShopShippingProfileUpgrade
            //val shopId : kotlin.Long = 789 // kotlin.Long | The unique positive non-zero numeric ID for an Etsy Shop.
            //val shippingProfileId : kotlin.Long = 789 // kotlin.Long | The numeric ID of the [shipping profile](/documentation/reference#operation/getShopShippingProfile) associated with the listing. Required when listing type is `physical`.
            //val type : kotlin.String = type_example // kotlin.String | The type of the shipping upgrade. Domestic (0) or international (1).
            //val upgradeName : kotlin.String = upgradeName_example // kotlin.String | Name for the shipping upgrade shown to shoppers at checkout, e.g. USPS Priority.
            //val price : kotlin.Float = 3.4 // kotlin.Float | Additional cost of adding the shipping upgrade.
            //val secondaryPrice : kotlin.Float = 3.4 // kotlin.Float | Additional cost of adding the shipping upgrade for each additional item.
            //val shippingCarrierId : kotlin.Int = 56 // kotlin.Int | The unique ID of a supported shipping carrier, which is used to calculate an Estimated Delivery Date. **Required with `mail_class`** if `min_delivery_days` and `max_delivery_days` are null.
            //val mailClass : kotlin.String = mailClass_example // kotlin.String | The unique ID string of a shipping carrier's mail class, which is used to calculate an estimated delivery date. **Required with `shipping_carrier_id`** if `min_delivery_days` and `max_delivery_days` are null.
            //val minDeliveryDays : kotlin.Int = 56 // kotlin.Int | The minimum number of business days a buyer can expect to wait to receive their purchased item once it has shipped. **Required with `max_delivery_days`** if `mail_class` is null.
            //val maxDeliveryDays : kotlin.Int = 56 // kotlin.Int | The maximum number of business days a buyer can expect to wait to receive their purchased item once it has shipped. **Required with `min_delivery_days`** if `mail_class` is null.
            //val result : ShopShippingProfileUpgrade = apiInstance.createShopShippingProfileUpgrade(shopId, shippingProfileId, type, upgradeName, price, secondaryPrice, shippingCarrierId, mailClass, minDeliveryDays, maxDeliveryDays)
            //result shouldBe ("TODO")
        }

        // to test deleteShopShippingProfile
        should("test deleteShopShippingProfile") {
            // uncomment below to test deleteShopShippingProfile
            //val shopId : kotlin.Long = 789 // kotlin.Long | The unique positive non-zero numeric ID for an Etsy Shop.
            //val shippingProfileId : kotlin.Long = 789 // kotlin.Long | The numeric ID of the [shipping profile](/documentation/reference#operation/getShopShippingProfile) associated with the listing. Required when listing type is `physical`.
            //apiInstance.deleteShopShippingProfile(shopId, shippingProfileId)
        }

        // to test deleteShopShippingProfileDestination
        should("test deleteShopShippingProfileDestination") {
            // uncomment below to test deleteShopShippingProfileDestination
            //val shopId : kotlin.Long = 789 // kotlin.Long | The unique positive non-zero numeric ID for an Etsy Shop.
            //val shippingProfileId : kotlin.Long = 789 // kotlin.Long | The numeric ID of the [shipping profile](/documentation/reference#operation/getShopShippingProfile) associated with the listing. Required when listing type is `physical`.
            //val shippingProfileDestinationId : kotlin.Long = 789 // kotlin.Long | The numeric ID of the shipping profile destination in the [shipping profile](/documentation/reference#tag/Shop-ShippingProfile) associated with the listing.
            //apiInstance.deleteShopShippingProfileDestination(shopId, shippingProfileId, shippingProfileDestinationId)
        }

        // to test deleteShopShippingProfileUpgrade
        should("test deleteShopShippingProfileUpgrade") {
            // uncomment below to test deleteShopShippingProfileUpgrade
            //val shopId : kotlin.Long = 789 // kotlin.Long | The unique positive non-zero numeric ID for an Etsy Shop.
            //val shippingProfileId : kotlin.Long = 789 // kotlin.Long | The numeric ID of the shipping profile.
            //val upgradeId : kotlin.Long = 789 // kotlin.Long | The numeric ID that is associated with a shipping upgrade
            //apiInstance.deleteShopShippingProfileUpgrade(shopId, shippingProfileId, upgradeId)
        }

        // to test getShippingCarriers
        should("test getShippingCarriers") {
            // uncomment below to test getShippingCarriers
            //val originCountryIso : kotlin.String = originCountryIso_example // kotlin.String | The ISO code of the country from which the listing ships.
            //val result : ShippingCarriers = apiInstance.getShippingCarriers(originCountryIso)
            //result shouldBe ("TODO")
        }

        // to test getShopShippingProfile
        should("test getShopShippingProfile") {
            // uncomment below to test getShopShippingProfile
            //val shopId : kotlin.Long = 789 // kotlin.Long | The unique positive non-zero numeric ID for an Etsy Shop.
            //val shippingProfileId : kotlin.Long = 789 // kotlin.Long | The numeric ID of the [shipping profile](/documentation/reference#operation/getShopShippingProfile) associated with the listing. Required when listing type is `physical`.
            //val result : ShopShippingProfile = apiInstance.getShopShippingProfile(shopId, shippingProfileId)
            //result shouldBe ("TODO")
        }

        // to test getShopShippingProfileDestinationsByShippingProfile
        should("test getShopShippingProfileDestinationsByShippingProfile") {
            // uncomment below to test getShopShippingProfileDestinationsByShippingProfile
            //val shopId : kotlin.Long = 789 // kotlin.Long | The unique positive non-zero numeric ID for an Etsy Shop.
            //val shippingProfileId : kotlin.Long = 789 // kotlin.Long | The numeric ID of the [shipping profile](/documentation/reference#operation/getShopShippingProfile) associated with the listing. Required when listing type is `physical`.
            //val limit : kotlin.Int = 56 // kotlin.Int | The maximum number of results to return.
            //val offset : kotlin.Int = 56 // kotlin.Int | The number of records to skip before selecting the first result.
            //val result : ShopShippingProfileDestinations = apiInstance.getShopShippingProfileDestinationsByShippingProfile(shopId, shippingProfileId, limit, offset)
            //result shouldBe ("TODO")
        }

        // to test getShopShippingProfileUpgrades
        should("test getShopShippingProfileUpgrades") {
            // uncomment below to test getShopShippingProfileUpgrades
            //val shopId : kotlin.Long = 789 // kotlin.Long | The unique positive non-zero numeric ID for an Etsy Shop.
            //val shippingProfileId : kotlin.Long = 789 // kotlin.Long | The numeric ID of the [shipping profile](/documentation/reference#operation/getShopShippingProfile) associated with the listing. Required when listing type is `physical`.
            //val result : ShopShippingProfileUpgrades = apiInstance.getShopShippingProfileUpgrades(shopId, shippingProfileId)
            //result shouldBe ("TODO")
        }

        // to test getShopShippingProfiles
        should("test getShopShippingProfiles") {
            // uncomment below to test getShopShippingProfiles
            //val shopId : kotlin.Long = 789 // kotlin.Long | The unique positive non-zero numeric ID for an Etsy Shop.
            //val result : ShopShippingProfiles = apiInstance.getShopShippingProfiles(shopId)
            //result shouldBe ("TODO")
        }

        // to test updateShopShippingProfile
        should("test updateShopShippingProfile") {
            // uncomment below to test updateShopShippingProfile
            //val shopId : kotlin.Long = 789 // kotlin.Long | The unique positive non-zero numeric ID for an Etsy Shop.
            //val shippingProfileId : kotlin.Long = 789 // kotlin.Long | The numeric ID of the [shipping profile](/documentation/reference#operation/getShopShippingProfile) associated with the listing. Required when listing type is `physical`.
            //val title : kotlin.String = title_example // kotlin.String | The name string of this shipping profile.
            //val originCountryIso : kotlin.String = originCountryIso_example // kotlin.String | The ISO code of the country from which the listing ships.
            //val minProcessingTime : kotlin.Int = 56 // kotlin.Int | The minimum time required to process to ship listings with this shipping profile.
            //val maxProcessingTime : kotlin.Int = 56 // kotlin.Int | The maximum processing time the listing needs to ship.
            //val processingTimeUnit : kotlin.String = processingTimeUnit_example // kotlin.String | The unit used to represent how long a processing time is. A week is equivalent to the set processing schedule (default to 5 business days). If none is provided, the unit is set to \\\"business_days\\\".
            //val originPostalCode : kotlin.String = originPostalCode_example // kotlin.String | The postal code string (not necessarily a number) for the location from which the listing ships. Required if the `origin_country_iso` supports postal codes. See the [Fulfillment Tutorial docs](https://developer.etsy.com/documentation/tutorials/fulfillment/#countries-requiring-postal-codes) for more info
            //val result : ShopShippingProfile = apiInstance.updateShopShippingProfile(shopId, shippingProfileId, title, originCountryIso, minProcessingTime, maxProcessingTime, processingTimeUnit, originPostalCode)
            //result shouldBe ("TODO")
        }

        // to test updateShopShippingProfileDestination
        should("test updateShopShippingProfileDestination") {
            // uncomment below to test updateShopShippingProfileDestination
            //val shopId : kotlin.Long = 789 // kotlin.Long | The unique positive non-zero numeric ID for an Etsy Shop.
            //val shippingProfileId : kotlin.Long = 789 // kotlin.Long | The numeric ID of the [shipping profile](/documentation/reference#operation/getShopShippingProfile) associated with the listing. Required when listing type is `physical`.
            //val shippingProfileDestinationId : kotlin.Long = 789 // kotlin.Long | The numeric ID of the shipping profile destination in the [shipping profile](/documentation/reference#tag/Shop-ShippingProfile) associated with the listing.
            //val primaryCost : kotlin.Float = 3.4 // kotlin.Float | The cost of shipping to this country/region alone, measured in the store's default currency.
            //val secondaryCost : kotlin.Float = 3.4 // kotlin.Float | The cost of shipping to this country/region with another item, measured in the store's default currency.
            //val destinationCountryIso : kotlin.String = destinationCountryIso_example // kotlin.String | The ISO code of the country to which the listing ships. If null, request sets destination to destination_region. Required if destination_region is null or not provided.
            //val destinationRegion : kotlin.String = destinationRegion_example // kotlin.String | The code of the region to which the listing ships. A region represents a set of countries. Supported regions are Europe Union and Non-Europe Union (countries in Europe not in EU). If `none`, request sets destination to destination_country_iso. Required if destination_country_iso is null or not provided.
            //val shippingCarrierId : kotlin.Int = 56 // kotlin.Int | The unique ID of a supported shipping carrier, which is used to calculate an Estimated Delivery Date. **Required with `mail_class`** if `min_delivery_days` and `max_delivery_days` are null.
            //val mailClass : kotlin.String = mailClass_example // kotlin.String | The unique ID string of a shipping carrier's mail class, which is used to calculate an estimated delivery date. **Required with `shipping_carrier_id`** if `min_delivery_days` and `max_delivery_days` are null.
            //val minDeliveryDays : kotlin.Int = 56 // kotlin.Int | The minimum number of business days a buyer can expect to wait to receive their purchased item once it has shipped. **Required with `max_delivery_days`** if `mail_class` is null.
            //val maxDeliveryDays : kotlin.Int = 56 // kotlin.Int | The maximum number of business days a buyer can expect to wait to receive their purchased item once it has shipped. **Required with `min_delivery_days`** if `mail_class` is null.
            //val result : ShopShippingProfileDestination = apiInstance.updateShopShippingProfileDestination(shopId, shippingProfileId, shippingProfileDestinationId, primaryCost, secondaryCost, destinationCountryIso, destinationRegion, shippingCarrierId, mailClass, minDeliveryDays, maxDeliveryDays)
            //result shouldBe ("TODO")
        }

        // to test updateShopShippingProfileUpgrade
        should("test updateShopShippingProfileUpgrade") {
            // uncomment below to test updateShopShippingProfileUpgrade
            //val shopId : kotlin.Long = 789 // kotlin.Long | The unique positive non-zero numeric ID for an Etsy Shop.
            //val shippingProfileId : kotlin.Long = 789 // kotlin.Long | The numeric ID of the [shipping profile](/documentation/reference#operation/getShopShippingProfile) associated with the listing. Required when listing type is `physical`.
            //val upgradeId : kotlin.Long = 789 // kotlin.Long | The numeric ID that is associated with a shipping upgrade
            //val upgradeName : kotlin.String = upgradeName_example // kotlin.String | Name for the shipping upgrade shown to shoppers at checkout, e.g. USPS Priority.
            //val type : kotlin.String = type_example // kotlin.String | The type of the shipping upgrade. Domestic (0) or international (1).
            //val price : kotlin.Float = 3.4 // kotlin.Float | Additional cost of adding the shipping upgrade.
            //val secondaryPrice : kotlin.Float = 3.4 // kotlin.Float | Additional cost of adding the shipping upgrade for each additional item.
            //val shippingCarrierId : kotlin.Int = 56 // kotlin.Int | The unique ID of a supported shipping carrier, which is used to calculate an Estimated Delivery Date. **Required with `mail_class`** if `min_delivery_days` and `max_delivery_days` are null.
            //val mailClass : kotlin.String = mailClass_example // kotlin.String | The unique ID string of a shipping carrier's mail class, which is used to calculate an estimated delivery date. **Required with `shipping_carrier_id`** if `min_delivery_days` and `max_delivery_days` are null.
            //val minDeliveryDays : kotlin.Int = 56 // kotlin.Int | The minimum number of business days a buyer can expect to wait to receive their purchased item once it has shipped. **Required with `max_delivery_days`** if `mail_class` is null.
            //val maxDeliveryDays : kotlin.Int = 56 // kotlin.Int | The maximum number of business days a buyer can expect to wait to receive their purchased item once it has shipped. **Required with `min_delivery_days`** if `mail_class` is null.
            //val result : ShopShippingProfileUpgrade = apiInstance.updateShopShippingProfileUpgrade(shopId, shippingProfileId, upgradeId, upgradeName, type, price, secondaryPrice, shippingCarrierId, mailClass, minDeliveryDays, maxDeliveryDays)
            //result shouldBe ("TODO")
        }

    }
}
