/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.etsy.apis.ShopListingVideoApi
import com.etsy.models.ErrorSchema
import com.etsy.models.ListingVideo
import com.etsy.models.ListingVideos

class ShopListingVideoApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ShopListingVideoApi
        //val apiInstance = ShopListingVideoApi()

        // to test deleteListingVideo
        should("test deleteListingVideo") {
            // uncomment below to test deleteListingVideo
            //val shopId : kotlin.Long = 789 // kotlin.Long | The unique positive non-zero numeric ID for an Etsy Shop.
            //val listingId : kotlin.Long = 789 // kotlin.Long | The numeric ID for the [listing](/documentation/reference#tag/ShopListing) associated to this transaction.
            //val videoId : kotlin.Long = 789 // kotlin.Long | The unique ID of a video associated with a listing.
            //apiInstance.deleteListingVideo(shopId, listingId, videoId)
        }

        // to test getListingVideo
        should("test getListingVideo") {
            // uncomment below to test getListingVideo
            //val videoId : kotlin.Long = 789 // kotlin.Long | The unique ID of a video associated with a listing.
            //val listingId : kotlin.Long = 789 // kotlin.Long | The numeric ID for the [listing](/documentation/reference#tag/ShopListing) associated to this transaction.
            //val result : ListingVideo = apiInstance.getListingVideo(videoId, listingId)
            //result shouldBe ("TODO")
        }

        // to test getListingVideos
        should("test getListingVideos") {
            // uncomment below to test getListingVideos
            //val listingId : kotlin.Long = 789 // kotlin.Long | The numeric ID for the [listing](/documentation/reference#tag/ShopListing) associated to this transaction.
            //val result : ListingVideos = apiInstance.getListingVideos(listingId)
            //result shouldBe ("TODO")
        }

        // to test uploadListingVideo
        should("test uploadListingVideo") {
            // uncomment below to test uploadListingVideo
            //val shopId : kotlin.Long = 789 // kotlin.Long | The unique positive non-zero numeric ID for an Etsy Shop.
            //val listingId : kotlin.Long = 789 // kotlin.Long | The numeric ID for the [listing](/documentation/reference#tag/ShopListing) associated to this transaction.
            //val videoId : kotlin.Long = 789 // kotlin.Long | The unique ID of a video associated with a listing.
            //val video : io.ktor.client.request.forms.FormPart<io.ktor.client.request.forms.InputProvider> = BINARY_DATA_HERE // io.ktor.client.request.forms.FormPart<io.ktor.client.request.forms.InputProvider> | A video file to upload.
            //val name : kotlin.String = name_example // kotlin.String | The file name string for the video to upload.
            //val result : ListingVideo = apiInstance.uploadListingVideo(shopId, listingId, videoId, video, name)
            //result shouldBe ("TODO")
        }

    }
}
