/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.etsy.apis.ShopApi
import com.etsy.models.ErrorSchema
import com.etsy.models.Shop
import com.etsy.models.Shops

class ShopApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ShopApi
        //val apiInstance = ShopApi()

        // to test findShops
        should("test findShops") {
            // uncomment below to test findShops
            //val shopName : kotlin.String = shopName_example // kotlin.String | The shop's name string.
            //val limit : kotlin.Int = 56 // kotlin.Int | The maximum number of results to return.
            //val offset : kotlin.Int = 56 // kotlin.Int | The number of records to skip before selecting the first result.
            //val result : Shops = apiInstance.findShops(shopName, limit, offset)
            //result shouldBe ("TODO")
        }

        // to test getShop
        should("test getShop") {
            // uncomment below to test getShop
            //val shopId : kotlin.Long = 789 // kotlin.Long | The unique positive non-zero numeric ID for an Etsy Shop.
            //val result : Shop = apiInstance.getShop(shopId)
            //result shouldBe ("TODO")
        }

        // to test getShopByOwnerUserId
        should("test getShopByOwnerUserId") {
            // uncomment below to test getShopByOwnerUserId
            //val userId : kotlin.Long = 789 // kotlin.Long | The numeric user ID of the [user](/documentation/reference#tag/User) who owns this shop.
            //val result : Shop = apiInstance.getShopByOwnerUserId(userId)
            //result shouldBe ("TODO")
        }

        // to test updateShop
        should("test updateShop") {
            // uncomment below to test updateShop
            //val shopId : kotlin.Long = 789 // kotlin.Long | The unique positive non-zero numeric ID for an Etsy Shop.
            //val title : kotlin.String = title_example // kotlin.String | A brief heading string for the shop's main page.
            //val announcement : kotlin.String = announcement_example // kotlin.String | An announcement string to buyers that displays on the shop's homepage.
            //val saleMessage : kotlin.String = saleMessage_example // kotlin.String | A message string sent to users who complete a purchase from this shop.
            //val digitalSaleMessage : kotlin.String = digitalSaleMessage_example // kotlin.String | A message string sent to users who purchase a digital item from this shop.
            //val policyAdditional : kotlin.String = policyAdditional_example // kotlin.String | The shop's additional policies string (may be blank).
            //val result : Shop = apiInstance.updateShop(shopId, title, announcement, saleMessage, digitalSaleMessage, policyAdditional)
            //result shouldBe ("TODO")
        }

    }
}
