/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.etsy.apis.UserApi
import com.etsy.models.ErrorSchema
import com.etsy.models.Self
import com.etsy.models.User

class UserApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UserApi
        //val apiInstance = UserApi()

        // to test getMe
        should("test getMe") {
            // uncomment below to test getMe
            //val result : Self = apiInstance.getMe()
            //result shouldBe ("TODO")
        }

        // to test getUser
        should("test getUser") {
            // uncomment below to test getUser
            //val userId : kotlin.Long = 789 // kotlin.Long | 
            //val result : User = apiInstance.getUser(userId)
            //result shouldBe ("TODO")
        }

    }
}
