/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.etsy.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.etsy.apis.UserAddressApi
import com.etsy.models.ErrorSchema
import com.etsy.models.UserAddress
import com.etsy.models.UserAddresses

class UserAddressApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UserAddressApi
        //val apiInstance = UserAddressApi()

        // to test deleteUserAddress
        should("test deleteUserAddress") {
            // uncomment below to test deleteUserAddress
            //val userAddressId : kotlin.Long = 789 // kotlin.Long | The numeric ID of the user's address.
            //apiInstance.deleteUserAddress(userAddressId)
        }

        // to test getUserAddress
        should("test getUserAddress") {
            // uncomment below to test getUserAddress
            //val userAddressId : kotlin.Long = 789 // kotlin.Long | The numeric ID of the user's address.
            //val result : UserAddress = apiInstance.getUserAddress(userAddressId)
            //result shouldBe ("TODO")
        }

        // to test getUserAddresses
        should("test getUserAddresses") {
            // uncomment below to test getUserAddresses
            //val limit : kotlin.Int = 56 // kotlin.Int | The maximum number of results to return.
            //val offset : kotlin.Int = 56 // kotlin.Int | The number of records to skip before selecting the first result.
            //val result : UserAddresses = apiInstance.getUserAddresses(limit, offset)
            //result shouldBe ("TODO")
        }

    }
}
